//
// File generated by rootcint at Wed Nov 13 09:13:40 2013

// Do NOT change. Changes will be lost next time file is generated
//

#define R__DICTIONARY_FILENAME BaseCint
#include "RConfig.h" //rootcint 4834
#if !defined(R__ACCESS_IN_SYMBOL)
//Break the privacy of classes -- Disabled for the moment
#define private public
#define protected public
#endif

// Since CINT ignores the std namespace, we need to do so in this file.
namespace std {} using namespace std;
#include "BaseCint.h"

#include "TClass.h"
#include "TBuffer.h"
#include "TMemberInspector.h"
#include "TError.h"

#ifndef G__ROOT
#define G__ROOT
#endif

#include "RtypesImp.h"
#include "TIsAProxy.h"
#include "TFileMergeInfo.h"

// START OF SHADOWS

namespace ROOT {
   namespace Shadow {
      #if !(defined(R__ACCESS_IN_SYMBOL) || defined(R__USE_SHADOW_CLASS))
      typedef ::Message Message;
      #else
      class Message  {
         public:
         //friend XX;
         // To force the creation of a virtual table, throw just in case.
         virtual ~Message() throw() {};
      };
      #endif

      #if !(defined(R__ACCESS_IN_SYMBOL) || defined(R__USE_SHADOW_CLASS))
      typedef ::decoder_base decoder_base;
      #else
      class decoder_base  {
         public:
         //friend XX;
         // To force the creation of a virtual table, throw just in case.
         virtual ~decoder_base() throw() {};
         char _buf[200]; ///< char buffer for message manipulation
         bool _verbosity[5]; ///< holder for enabled message levels
         ::MSG::Level _verbosity_level; ///< holder for specified verbosity level
         string _name; ///< class name holder
      };
      #endif

   } // of namespace Shadow
} // of namespace ROOT
// END OF SHADOWS

namespace PMT {
   namespace ROOT {
      inline ::ROOT::TGenericClassInfo *GenerateInitInstance();
      static void PMT_Dictionary();

      // Function generating the singleton type initializer
      inline ::ROOT::TGenericClassInfo *GenerateInitInstance()
      {
         static ::ROOT::TGenericClassInfo 
            instance("PMT", 0 /*version*/, "./constants.hh", 69,
                     ::ROOT::DefineBehavior((void*)0,(void*)0),
                     &PMT_Dictionary, 0);
         return &instance;
      }
      // Insure that the inline function is _not_ optimized away by the compiler
      ::ROOT::TGenericClassInfo *(*_R__UNIQUE_(InitFunctionKeeper))() = &GenerateInitInstance;  
      // Static variable to force the class initialization
      static ::ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstance(); R__UseDummy(_R__UNIQUE_(Init));

      // Dictionary for non-ClassDef classes
      static void PMT_Dictionary() {
         GenerateInitInstance()->GetClass();
      }

   }
}

namespace MSG {
   namespace ROOT {
      inline ::ROOT::TGenericClassInfo *GenerateInitInstance();
      static void MSG_Dictionary();

      // Function generating the singleton type initializer
      inline ::ROOT::TGenericClassInfo *GenerateInitInstance()
      {
         static ::ROOT::TGenericClassInfo 
            instance("MSG", 0 /*version*/, "./constants.hh", 21,
                     ::ROOT::DefineBehavior((void*)0,(void*)0),
                     &MSG_Dictionary, 0);
         return &instance;
      }
      // Insure that the inline function is _not_ optimized away by the compiler
      ::ROOT::TGenericClassInfo *(*_R__UNIQUE_(InitFunctionKeeper))() = &GenerateInitInstance;  
      // Static variable to force the class initialization
      static ::ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstance(); R__UseDummy(_R__UNIQUE_(Init));

      // Dictionary for non-ClassDef classes
      static void MSG_Dictionary() {
         GenerateInitInstance()->GetClass();
      }

   }
}

namespace FORMAT {
   namespace ROOT {
      inline ::ROOT::TGenericClassInfo *GenerateInitInstance();
      static void FORMAT_Dictionary();

      // Function generating the singleton type initializer
      inline ::ROOT::TGenericClassInfo *GenerateInitInstance()
      {
         static ::ROOT::TGenericClassInfo 
            instance("FORMAT", 0 /*version*/, "./constants.hh", 55,
                     ::ROOT::DefineBehavior((void*)0,(void*)0),
                     &FORMAT_Dictionary, 0);
         return &instance;
      }
      // Insure that the inline function is _not_ optimized away by the compiler
      ::ROOT::TGenericClassInfo *(*_R__UNIQUE_(InitFunctionKeeper))() = &GenerateInitInstance;  
      // Static variable to force the class initialization
      static ::ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstance(); R__UseDummy(_R__UNIQUE_(Init));

      // Dictionary for non-ClassDef classes
      static void FORMAT_Dictionary() {
         GenerateInitInstance()->GetClass();
      }

   }
}

namespace DATA_STRUCT {
   namespace ROOT {
      inline ::ROOT::TGenericClassInfo *GenerateInitInstance();
      static void DATA_STRUCT_Dictionary();

      // Function generating the singleton type initializer
      inline ::ROOT::TGenericClassInfo *GenerateInitInstance()
      {
         static ::ROOT::TGenericClassInfo 
            instance("DATA_STRUCT", 0 /*version*/, "./constants.hh", 118,
                     ::ROOT::DefineBehavior((void*)0,(void*)0),
                     &DATA_STRUCT_Dictionary, 0);
         return &instance;
      }
      // Insure that the inline function is _not_ optimized away by the compiler
      ::ROOT::TGenericClassInfo *(*_R__UNIQUE_(InitFunctionKeeper))() = &GenerateInitInstance;  
      // Static variable to force the class initialization
      static ::ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstance(); R__UseDummy(_R__UNIQUE_(Init));

      // Dictionary for non-ClassDef classes
      static void DATA_STRUCT_Dictionary() {
         GenerateInitInstance()->GetClass();
      }

   }
}

namespace ROOT {
   void Message_ShowMembers(void *obj, TMemberInspector &R__insp);
   static void Message_Dictionary();

   // Function generating the singleton type initializer
   static TGenericClassInfo *GenerateInitInstanceLocal(const ::Message*)
   {
      // Make sure the shadow class has the right sizeof
      R__ASSERT(sizeof(::Message) == sizeof(::ROOT::Shadow::Message));
      ::Message *ptr = 0;
      static ::TVirtualIsAProxy* isa_proxy = new ::TIsAProxy(typeid(::Message),0);
      static ::ROOT::TGenericClassInfo 
         instance("Message", "./messenger.hh", 27,
                  typeid(::Message), DefineBehavior(ptr, ptr),
                  &Message_ShowMembers, &Message_Dictionary, isa_proxy, 4,
                  sizeof(::Message) );
      return &instance;
   }
   TGenericClassInfo *GenerateInitInstance(const ::Message*)
   {
      return GenerateInitInstanceLocal((::Message*)0);
   }
   // Static variable to force the class initialization
   static ::ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstanceLocal((const ::Message*)0x0); R__UseDummy(_R__UNIQUE_(Init));

   // Dictionary for non-ClassDef classes
   static void Message_Dictionary() {
      ::ROOT::GenerateInitInstanceLocal((const ::Message*)0x0)->GetClass();
   }

} // end of namespace ROOT

namespace ROOT {
   void decoder_base_ShowMembers(void *obj, TMemberInspector &R__insp);
   static void decoder_base_Dictionary();
   static void *new_decoder_base(void *p = 0);
   static void *newArray_decoder_base(Long_t size, void *p);
   static void delete_decoder_base(void *p);
   static void deleteArray_decoder_base(void *p);
   static void destruct_decoder_base(void *p);

   // Function generating the singleton type initializer
   static TGenericClassInfo *GenerateInitInstanceLocal(const ::decoder_base*)
   {
      // Make sure the shadow class has the right sizeof
      R__ASSERT(sizeof(::decoder_base) == sizeof(::ROOT::Shadow::decoder_base));
      ::decoder_base *ptr = 0;
      static ::TVirtualIsAProxy* isa_proxy = new ::TIsAProxy(typeid(::decoder_base),0);
      static ::ROOT::TGenericClassInfo 
         instance("decoder_base", "./decoder_base.hh", 26,
                  typeid(::decoder_base), DefineBehavior(ptr, ptr),
                  &decoder_base_ShowMembers, &decoder_base_Dictionary, isa_proxy, 4,
                  sizeof(::decoder_base) );
      instance.SetNew(&new_decoder_base);
      instance.SetNewArray(&newArray_decoder_base);
      instance.SetDelete(&delete_decoder_base);
      instance.SetDeleteArray(&deleteArray_decoder_base);
      instance.SetDestructor(&destruct_decoder_base);
      return &instance;
   }
   TGenericClassInfo *GenerateInitInstance(const ::decoder_base*)
   {
      return GenerateInitInstanceLocal((::decoder_base*)0);
   }
   // Static variable to force the class initialization
   static ::ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstanceLocal((const ::decoder_base*)0x0); R__UseDummy(_R__UNIQUE_(Init));

   // Dictionary for non-ClassDef classes
   static void decoder_base_Dictionary() {
      ::ROOT::GenerateInitInstanceLocal((const ::decoder_base*)0x0)->GetClass();
   }

} // end of namespace ROOT

//______________________________________________________________________________
namespace ROOT {
   void Message_ShowMembers(void *obj, TMemberInspector &R__insp)
   {
      // Inspect the data members of an object of class Message.
      typedef ::ROOT::Shadow::Message ShadowClass;
      ShadowClass *sobj = (ShadowClass*)obj;
      if (sobj) { } // Dummy usage just in case there is no datamember.

      TClass *R__cl  = ::ROOT::GenerateInitInstanceLocal((const ::Message*)0x0)->GetClass();
      if (R__cl || R__insp.IsA()) { }
   }

}

namespace ROOT {
} // end of namespace ROOT for class ::Message

//______________________________________________________________________________
namespace ROOT {
   void decoder_base_ShowMembers(void *obj, TMemberInspector &R__insp)
   {
      // Inspect the data members of an object of class decoder_base.
      typedef ::ROOT::Shadow::decoder_base ShadowClass;
      ShadowClass *sobj = (ShadowClass*)obj;
      if (sobj) { } // Dummy usage just in case there is no datamember.

      TClass *R__cl  = ::ROOT::GenerateInitInstanceLocal((const ::decoder_base*)0x0)->GetClass();
      if (R__cl || R__insp.IsA()) { }
      R__insp.Inspect(R__cl, R__insp.GetParent(), "_buf[200]", sobj->_buf);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "_verbosity[5]", sobj->_verbosity);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "_verbosity_level", &sobj->_verbosity_level);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "_name", (void*)&sobj->_name);
      R__insp.InspectMember("string", (void*)&sobj->_name, "_name.", false);
   }

}

namespace ROOT {
   // Wrappers around operator new
   static void *new_decoder_base(void *p) {
      return  p ? ::new((::ROOT::TOperatorNewHelper*)p) ::decoder_base : new ::decoder_base;
   }
   static void *newArray_decoder_base(Long_t nElements, void *p) {
      return p ? ::new((::ROOT::TOperatorNewHelper*)p) ::decoder_base[nElements] : new ::decoder_base[nElements];
   }
   // Wrapper around operator delete
   static void delete_decoder_base(void *p) {
      delete ((::decoder_base*)p);
   }
   static void deleteArray_decoder_base(void *p) {
      delete [] ((::decoder_base*)p);
   }
   static void destruct_decoder_base(void *p) {
      typedef ::decoder_base current_t;
      ((current_t*)p)->~current_t();
   }
} // end of namespace ROOT for class ::decoder_base

/********************************************************
* BaseCint.cc
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************/

#ifdef G__MEMTEST
#undef malloc
#undef free
#endif

#if defined(__GNUC__) && __GNUC__ >= 4 && ((__GNUC_MINOR__ == 2 && __GNUC_PATCHLEVEL__ >= 1) || (__GNUC_MINOR__ >= 3))
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif

extern "C" void G__cpp_reset_tagtableBaseCint();

extern "C" void G__set_cpp_environmentBaseCint() {
  G__add_compiledheader("TObject.h");
  G__add_compiledheader("TMemberInspector.h");
  G__add_compiledheader("Base-TypeDef.hh");
  G__add_compiledheader("constants.hh");
  G__add_compiledheader("decoder_base.hh");
  G__add_compiledheader("messenger.hh");
  G__add_compiledheader("types.hh");
  G__cpp_reset_tagtableBaseCint();
}
#include <new>
extern "C" int G__cpp_dllrevBaseCint() { return(30051515); }

/*********************************************************
* Member function Interface Method
*********************************************************/

/* PMT */

/* MSG */

/* FORMAT */

/* DATA_STRUCT */

/* Message */
static int G__BaseCint_224_0_2(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 85, (long) ((Message*) G__getstructoffset())->get());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__BaseCint_224_0_3(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      Message::send((MSG::Level) G__int(libp->para[0]), *((string*) G__int(libp->para[1])));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__BaseCint_224_0_4(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      Message::send((MSG::Level) G__int(libp->para[0]), *((string*) G__int(libp->para[1]))
, *((string*) G__int(libp->para[2])));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic copy constructor
static int G__BaseCint_224_0_5(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)

{
   Message* p;
   void* tmp = (void*) G__int(libp->para[0]);
   p = new Message(*(Message*) tmp);
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__BaseCintLN_Message));
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic assignment operator
static int G__BaseCint_224_0_6(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   Message* dest = (Message*) G__getstructoffset();
   *dest = *(Message*) libp->para[0].ref;
   const Message& obj = *dest;
   result7->ref = (long) (&obj);
   result7->obj.i = (long) (&obj);
   return(1 || funcname || hash || result7 || libp) ;
}


/* decoder_base */
static int G__BaseCint_225_0_1(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   decoder_base* p = NULL;
   char* gvp = (char*) G__getgvp();
   int n = G__getaryconstruct();
   if (n) {
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new decoder_base[n];
     } else {
       p = new((void*) gvp) decoder_base[n];
     }
   } else {
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new decoder_base;
     } else {
       p = new((void*) gvp) decoder_base;
     }
   }
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__BaseCintLN_decoder_base));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__BaseCint_225_0_2(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   decoder_base* p = NULL;
   char* gvp = (char*) G__getgvp();
   //m: 1
   if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
     p = new decoder_base(*(decoder_base*) libp->para[0].ref);
   } else {
     p = new((void*) gvp) decoder_base(*(decoder_base*) libp->para[0].ref);
   }
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__BaseCintLN_decoder_base));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__BaseCint_225_0_3(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((decoder_base*) G__getstructoffset())->set_verbosity((MSG::Level) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__BaseCint_225_0_4(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) ((const decoder_base*) G__getstructoffset())->get_verbosity());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__BaseCint_225_0_5(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      {
         const string* pobj;
         const string xobj = ((const decoder_base*) G__getstructoffset())->class_name();
         pobj = new string(xobj);
         result7->obj.i = (long) ((void*) pobj);
         result7->ref = result7->obj.i;
         G__store_tempobject(*result7);
      }
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic destructor
typedef decoder_base G__Tdecoder_base;
static int G__BaseCint_225_0_6(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   char* gvp = (char*) G__getgvp();
   long soff = G__getstructoffset();
   int n = G__getaryconstruct();
   //
   //has_a_delete: 0
   //has_own_delete1arg: 0
   //has_own_delete2arg: 0
   //
   if (!soff) {
     return(1);
   }
   if (n) {
     if (gvp == (char*)G__PVOID) {
       delete[] (decoder_base*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       for (int i = n - 1; i >= 0; --i) {
         ((decoder_base*) (soff+(sizeof(decoder_base)*i)))->~G__Tdecoder_base();
       }
       G__setgvp((long)gvp);
     }
   } else {
     if (gvp == (char*)G__PVOID) {
       delete (decoder_base*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       ((decoder_base*) (soff))->~G__Tdecoder_base();
       G__setgvp((long)gvp);
     }
   }
   G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic assignment operator
static int G__BaseCint_225_0_7(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   decoder_base* dest = (decoder_base*) G__getstructoffset();
   *dest = *(decoder_base*) libp->para[0].ref;
   const decoder_base& obj = *dest;
   result7->ref = (long) (&obj);
   result7->obj.i = (long) (&obj);
   return(1 || funcname || hash || result7 || libp) ;
}


/* Setting up global function */

/*********************************************************
* Member function Stub
*********************************************************/

/* PMT */

/* MSG */

/* FORMAT */

/* DATA_STRUCT */

/* Message */

/* decoder_base */

/*********************************************************
* Global function Stub
*********************************************************/

/*********************************************************
* Get size of pointer to member function
*********************************************************/
class G__Sizep2memfuncBaseCint {
 public:
  G__Sizep2memfuncBaseCint(): p(&G__Sizep2memfuncBaseCint::sizep2memfunc) {}
    size_t sizep2memfunc() { return(sizeof(p)); }
  private:
    size_t (G__Sizep2memfuncBaseCint::*p)();
};

size_t G__get_sizep2memfuncBaseCint()
{
  G__Sizep2memfuncBaseCint a;
  G__setsizep2memfunc((int)a.sizep2memfunc());
  return((size_t)a.sizep2memfunc());
}


/*********************************************************
* virtual base class offset calculation interface
*********************************************************/

   /* Setting up class inheritance */

/*********************************************************
* Inheritance information setup/
*********************************************************/
extern "C" void G__cpp_setup_inheritanceBaseCint() {

   /* Setting up class inheritance */
}

/*********************************************************
* typedef information setup/
*********************************************************/
extern "C" void G__cpp_setup_typetableBaseCint() {

   /* Setting up typedef entry */
   G__search_typename2("vector<ROOT::TSchemaHelper>",117,G__get_linked_tagnum(&G__BaseCintLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__BaseCintLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__BaseCintLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__BaseCintLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__BaseCintLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<TVirtualArray*>",117,G__get_linked_tagnum(&G__BaseCintLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__BaseCintLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__BaseCintLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__BaseCintLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__BaseCintLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<std::bidirectional_iterator_tag,TObject*,std::ptrdiff_t,const TObject**,const TObject*&>",117,G__get_linked_tagnum(&G__BaseCintLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*,std::ptrdiff_t,const TObject**,const TObject*&>",117,G__get_linked_tagnum(&G__BaseCintLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*>",117,G__get_linked_tagnum(&G__BaseCintLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*,long>",117,G__get_linked_tagnum(&G__BaseCintLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*,long,const TObject**>",117,G__get_linked_tagnum(&G__BaseCintLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("semapho_t",104,-1,0,G__get_linked_tagnum(&G__BaseCintLN_PMT));
   G__setnewtype(-1,"/< Used for semapho",0);
   G__search_typename2("word_t",104,-1,0,G__get_linked_tagnum(&G__BaseCintLN_PMT));
   G__setnewtype(-1,"/< Used as a data word format for the PMT electronics",0);
   G__search_typename2("timeslice_t",114,-1,0,G__get_linked_tagnum(&G__BaseCintLN_PMT));
   G__setnewtype(-1,"/< Used as a unit of digitized time",0);
   G__search_typename2("ch_adc_t",114,-1,0,G__get_linked_tagnum(&G__BaseCintLN_PMT));
   G__setnewtype(-1,"/< Used as a unit of digitized ADC count",0);
   G__search_typename2("ch_number_t",114,-1,0,G__get_linked_tagnum(&G__BaseCintLN_PMT));
   G__setnewtype(-1,"/< Channel number type definition",0);
   G__search_typename2("vector<ch_adc_t>",117,G__get_linked_tagnum(&G__BaseCintLN_vectorlEunsignedsPshortcOallocatorlEunsignedsPshortgRsPgR),0,G__get_linked_tagnum(&G__BaseCintLN_PMT));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("ch_waveform_t",117,G__get_linked_tagnum(&G__BaseCintLN_vectorlEunsignedsPshortcOallocatorlEunsignedsPshortgRsPgR),0,G__get_linked_tagnum(&G__BaseCintLN_PMT));
   G__setnewtype(-1,"/< Channel waveform type definition",0);
}

/*********************************************************
* Data Member information setup/
*********************************************************/

   /* Setting up class,struct,union tag member variable */

   /* PMT */
static void G__setup_memvarPMT(void) {
   G__tag_memvar_setup(G__get_linked_tagnum(&G__BaseCintLN_PMT));
   {
   G__memvar_setup((void*)(&PMT::INVALID_CH),114,0,1,-1,G__defined_typename("ch_number_t"),-1,1,"INVALID_CH=",0,"/< Invalid (or initialized) channel number");
   G__memvar_setup((void*)(&PMT::INVALID_WORD),104,0,1,-1,G__defined_typename("word_t"),-1,1,"INVALID_WORD=",0,"/< Invalid (or initialized) event word");
   G__memvar_setup((void*)(&PMT::EMPTY_WORD),104,0,1,-1,G__defined_typename("word_t"),-1,1,"EMPTY_WORD=",0,"/< Empty word");
   G__memvar_setup((void*)(&PMT::BEAMGATE_NSAMPLE),104,0,1,-1,G__defined_typename("word_t"),-1,1,"BEAMGATE_NSAMPLE=",0,"/< # samples in the beamgate");
   G__memvar_setup((void*)(&PMT::NUM_PMT_CHANNEL),114,0,1,-1,G__defined_typename("ch_number_t"),-1,1,"NUM_PMT_CHANNEL=",0,"/< # of PMT readout channels");
   G__memvar_setup((void*)(&PMT::MAX_ADC),114,0,1,-1,G__defined_typename("ch_adc_t"),-1,1,"MAX_ADC=",0,"/< Maximum ADC value");
   G__memvar_setup((void*)G__PVOID,105,0,1,G__get_linked_tagnum(&G__BaseCintLN_PMTcLcLDISCRIMINATOR),-1,-2,1,G__FastAllocString(2048).Format("BASE_DISC=%lldLL",(long long)PMT::BASE_DISC).data(),0,(char*)NULL);
   G__memvar_setup((void*)G__PVOID,105,0,1,G__get_linked_tagnum(&G__BaseCintLN_PMTcLcLDISCRIMINATOR),-1,-2,1,G__FastAllocString(2048).Format("COSMIC_DISC=%lldLL",(long long)PMT::COSMIC_DISC).data(),0,(char*)NULL);
   G__memvar_setup((void*)G__PVOID,105,0,1,G__get_linked_tagnum(&G__BaseCintLN_PMTcLcLDISCRIMINATOR),-1,-2,1,G__FastAllocString(2048).Format("MICHEL_DISC=%lldLL",(long long)PMT::MICHEL_DISC).data(),0,(char*)NULL);
   G__memvar_setup((void*)G__PVOID,105,0,1,G__get_linked_tagnum(&G__BaseCintLN_PMTcLcLDISCRIMINATOR),-1,-2,1,G__FastAllocString(2048).Format("BEAM_DISC=%lldLL",(long long)PMT::BEAM_DISC).data(),0,(char*)NULL);
   G__memvar_setup((void*)G__PVOID,105,0,1,G__get_linked_tagnum(&G__BaseCintLN_PMTcLcLDISCRIMINATOR),-1,-2,1,G__FastAllocString(2048).Format("BEAM_WIN=%lldLL",(long long)PMT::BEAM_WIN).data(),0,(char*)NULL);
   G__memvar_setup((void*)G__PVOID,105,0,1,G__get_linked_tagnum(&G__BaseCintLN_PMTcLcLDISCRIMINATOR),-1,-2,1,G__FastAllocString(2048).Format("DISC_MAX=%lldLL",(long long)PMT::DISC_MAX).data(),0,(char*)NULL);
   G__memvar_setup((void*)G__PVOID,105,0,1,G__get_linked_tagnum(&G__BaseCintLN_PMTcLcLPMT_WORD),-1,-2,1,G__FastAllocString(2048).Format("UNDEFINED_WORD=%lldLL",(long long)PMT::UNDEFINED_WORD).data(),0,(char*)NULL);
   G__memvar_setup((void*)G__PVOID,105,0,1,G__get_linked_tagnum(&G__BaseCintLN_PMTcLcLPMT_WORD),-1,-2,1,G__FastAllocString(2048).Format("EVENT_HEADER=%lldLL",(long long)PMT::EVENT_HEADER).data(),0,(char*)NULL);
   G__memvar_setup((void*)G__PVOID,105,0,1,G__get_linked_tagnum(&G__BaseCintLN_PMTcLcLPMT_WORD),-1,-2,1,G__FastAllocString(2048).Format("FEM_HEADER=%lldLL",(long long)PMT::FEM_HEADER).data(),0,(char*)NULL);
   G__memvar_setup((void*)G__PVOID,105,0,1,G__get_linked_tagnum(&G__BaseCintLN_PMTcLcLPMT_WORD),-1,-2,1,G__FastAllocString(2048).Format("FEM_FIRST_WORD=%lldLL",(long long)PMT::FEM_FIRST_WORD).data(),0,(char*)NULL);
   G__memvar_setup((void*)G__PVOID,105,0,1,G__get_linked_tagnum(&G__BaseCintLN_PMTcLcLPMT_WORD),-1,-2,1,G__FastAllocString(2048).Format("CHANNEL_HEADER=%lldLL",(long long)PMT::CHANNEL_HEADER).data(),0,(char*)NULL);
   G__memvar_setup((void*)G__PVOID,105,0,1,G__get_linked_tagnum(&G__BaseCintLN_PMTcLcLPMT_WORD),-1,-2,1,G__FastAllocString(2048).Format("CHANNEL_WORD=%lldLL",(long long)PMT::CHANNEL_WORD).data(),0,(char*)NULL);
   G__memvar_setup((void*)G__PVOID,105,0,1,G__get_linked_tagnum(&G__BaseCintLN_PMTcLcLPMT_WORD),-1,-2,1,G__FastAllocString(2048).Format("CHANNEL_LAST_WORD=%lldLL",(long long)PMT::CHANNEL_LAST_WORD).data(),0,(char*)NULL);
   G__memvar_setup((void*)G__PVOID,105,0,1,G__get_linked_tagnum(&G__BaseCintLN_PMTcLcLPMT_WORD),-1,-2,1,G__FastAllocString(2048).Format("FEM_LAST_WORD=%lldLL",(long long)PMT::FEM_LAST_WORD).data(),0,(char*)NULL);
   G__memvar_setup((void*)G__PVOID,105,0,1,G__get_linked_tagnum(&G__BaseCintLN_PMTcLcLPMT_WORD),-1,-2,1,G__FastAllocString(2048).Format("EVENT_LAST_WORD=%lldLL",(long long)PMT::EVENT_LAST_WORD).data(),0,(char*)NULL);
   }
   G__tag_memvar_reset();
}


   /* MSG */
static void G__setup_memvarMSG(void) {
   G__tag_memvar_setup(G__get_linked_tagnum(&G__BaseCintLN_MSG));
   {
   G__memvar_setup((void*)G__PVOID,105,0,1,G__get_linked_tagnum(&G__BaseCintLN_MSGcLcLLevel),-1,-2,1,G__FastAllocString(2048).Format("DEBUG=%lldLL",(long long)MSG::DEBUG).data(),0,(char*)NULL);
   G__memvar_setup((void*)G__PVOID,105,0,1,G__get_linked_tagnum(&G__BaseCintLN_MSGcLcLLevel),-1,-2,1,G__FastAllocString(2048).Format("INFO=%lldLL",(long long)MSG::INFO).data(),0,(char*)NULL);
   G__memvar_setup((void*)G__PVOID,105,0,1,G__get_linked_tagnum(&G__BaseCintLN_MSGcLcLLevel),-1,-2,1,G__FastAllocString(2048).Format("NORMAL=%lldLL",(long long)MSG::NORMAL).data(),0,(char*)NULL);
   G__memvar_setup((void*)G__PVOID,105,0,1,G__get_linked_tagnum(&G__BaseCintLN_MSGcLcLLevel),-1,-2,1,G__FastAllocString(2048).Format("WARNING=%lldLL",(long long)MSG::WARNING).data(),0,(char*)NULL);
   G__memvar_setup((void*)G__PVOID,105,0,1,G__get_linked_tagnum(&G__BaseCintLN_MSGcLcLLevel),-1,-2,1,G__FastAllocString(2048).Format("ERROR=%lldLL",(long long)MSG::ERROR).data(),0,(char*)NULL);
   G__memvar_setup((void*)G__PVOID,105,0,1,G__get_linked_tagnum(&G__BaseCintLN_MSGcLcLLevel),-1,-2,1,G__FastAllocString(2048).Format("MSG_TYPE_MAX=%lldLL",(long long)MSG::MSG_TYPE_MAX).data(),0,(char*)NULL);
   G__memvar_setup((void*)(&MSG::ColorPrefix),117,0,1,G__get_linked_tagnum(&G__BaseCintLN_string),-1,-5,1,"ColorPrefix[5]=",0,(char*)NULL);
   G__memvar_setup((void*)(&MSG::StringPrefix),117,0,1,G__get_linked_tagnum(&G__BaseCintLN_string),-1,-5,1,"StringPrefix[5]=",0,(char*)NULL);
   }
   G__tag_memvar_reset();
}


   /* FORMAT */
static void G__setup_memvarFORMAT(void) {
   G__tag_memvar_setup(G__get_linked_tagnum(&G__BaseCintLN_FORMAT));
   {
   G__memvar_setup((void*)G__PVOID,105,0,1,G__get_linked_tagnum(&G__BaseCintLN_FORMATcLcLINPUT_FILE),-1,-2,1,G__FastAllocString(2048).Format("BINARY=%lldLL",(long long)FORMAT::BINARY).data(),0,(char*)NULL);
   G__memvar_setup((void*)G__PVOID,105,0,1,G__get_linked_tagnum(&G__BaseCintLN_FORMATcLcLINPUT_FILE),-1,-2,1,G__FastAllocString(2048).Format("ASCII=%lldLL",(long long)FORMAT::ASCII).data(),0,(char*)NULL);
   G__memvar_setup((void*)G__PVOID,105,0,1,G__get_linked_tagnum(&G__BaseCintLN_FORMATcLcLINPUT_FILE),-1,-2,1,G__FastAllocString(2048).Format("UNDEFINED=%lldLL",(long long)FORMAT::UNDEFINED).data(),0,(char*)NULL);
   }
   G__tag_memvar_reset();
}


   /* DATA_STRUCT */
static void G__setup_memvarDATA_STRUCT(void) {
   G__tag_memvar_setup(G__get_linked_tagnum(&G__BaseCintLN_DATA_STRUCT));
   {
   G__memvar_setup((void*)G__PVOID,105,0,1,G__get_linked_tagnum(&G__BaseCintLN_DATA_STRUCTcLcLDATA_TYPE),-1,-2,1,G__FastAllocString(2048).Format("PMT_WF_COLLECTION=%lldLL",(long long)DATA_STRUCT::PMT_WF_COLLECTION).data(),0,(char*)NULL);
   G__memvar_setup((void*)G__PVOID,105,0,1,G__get_linked_tagnum(&G__BaseCintLN_DATA_STRUCTcLcLDATA_TYPE),-1,-2,1,G__FastAllocString(2048).Format("TPC_WF_COLLECTION=%lldLL",(long long)DATA_STRUCT::TPC_WF_COLLECTION).data(),0,(char*)NULL);
   G__memvar_setup((void*)G__PVOID,105,0,1,G__get_linked_tagnum(&G__BaseCintLN_DATA_STRUCTcLcLDATA_TYPE),-1,-2,1,G__FastAllocString(2048).Format("TRIG_INFO=%lldLL",(long long)DATA_STRUCT::TRIG_INFO).data(),0,(char*)NULL);
   G__memvar_setup((void*)G__PVOID,105,0,1,G__get_linked_tagnum(&G__BaseCintLN_DATA_STRUCTcLcLDATA_TYPE),-1,-2,1,G__FastAllocString(2048).Format("PULSE_COLLECTION=%lldLL",(long long)DATA_STRUCT::PULSE_COLLECTION).data(),0,(char*)NULL);
   G__memvar_setup((void*)G__PVOID,105,0,1,G__get_linked_tagnum(&G__BaseCintLN_DATA_STRUCTcLcLDATA_TYPE),-1,-2,1,G__FastAllocString(2048).Format("FIXED_WIN_PULSE_COLLECTION=%lldLL",(long long)DATA_STRUCT::FIXED_WIN_PULSE_COLLECTION).data(),0,(char*)NULL);
   G__memvar_setup((void*)G__PVOID,105,0,1,G__get_linked_tagnum(&G__BaseCintLN_DATA_STRUCTcLcLDATA_TYPE),-1,-2,1,G__FastAllocString(2048).Format("THRES_WIN_PULSE_COLLECTION=%lldLL",(long long)DATA_STRUCT::THRES_WIN_PULSE_COLLECTION).data(),0,(char*)NULL);
   G__memvar_setup((void*)G__PVOID,105,0,1,G__get_linked_tagnum(&G__BaseCintLN_DATA_STRUCTcLcLDATA_TYPE),-1,-2,1,G__FastAllocString(2048).Format("SLIDE_WIN_PULSE_COLLECTION=%lldLL",(long long)DATA_STRUCT::SLIDE_WIN_PULSE_COLLECTION).data(),0,(char*)NULL);
   G__memvar_setup((void*)G__PVOID,105,0,1,G__get_linked_tagnum(&G__BaseCintLN_DATA_STRUCTcLcLDATA_TYPE),-1,-2,1,G__FastAllocString(2048).Format("USER_COLLECTION=%lldLL",(long long)DATA_STRUCT::USER_COLLECTION).data(),0,(char*)NULL);
   G__memvar_setup((void*)G__PVOID,105,0,1,G__get_linked_tagnum(&G__BaseCintLN_DATA_STRUCTcLcLDATA_TYPE),-1,-2,1,G__FastAllocString(2048).Format("DATA_TYPE_MAX=%lldLL",(long long)DATA_STRUCT::DATA_TYPE_MAX).data(),0,(char*)NULL);
   G__memvar_setup((void*)(&DATA_STRUCT::DATA_TREE_NAME),117,0,1,G__get_linked_tagnum(&G__BaseCintLN_string),-1,-5,1,"DATA_TREE_NAME[8]=",0,(char*)NULL);
   }
   G__tag_memvar_reset();
}


   /* Message */
static void G__setup_memvarMessage(void) {
   G__tag_memvar_setup(G__get_linked_tagnum(&G__BaseCintLN_Message));
   { Message *p; p=(Message*)0x1000; if (p) { }
   G__memvar_setup((void*)0,108,0,0,-1,-1,-1,4,"G__virtualinfo=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__BaseCintLN_Message),-1,-2,4,"me=",0,(char*)NULL);
   }
   G__tag_memvar_reset();
}


   /* decoder_base */
static void G__setup_memvardecoder_base(void) {
   G__tag_memvar_setup(G__get_linked_tagnum(&G__BaseCintLN_decoder_base));
   { decoder_base *p; p=(decoder_base*)0x1000; if (p) { }
   G__memvar_setup((void*)0,108,0,0,-1,-1,-1,4,"G__virtualinfo=",0,(char*)NULL);
   G__memvar_setup((void*)0,99,0,0,-1,-1,-1,2,"_buf[200]=",0,"/< char buffer for message manipulation");
   G__memvar_setup((void*)0,103,0,0,-1,-1,-1,2,"_verbosity[5]=",0,"/< holder for enabled message levels");
   G__memvar_setup((void*)0,105,0,0,G__get_linked_tagnum(&G__BaseCintLN_MSGcLcLLevel),-1,-1,2,"_verbosity_level=",0,"/< holder for specified verbosity level");
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__BaseCintLN_string),-1,-1,2,"_name=",0,"/< class name holder");
   }
   G__tag_memvar_reset();
}

extern "C" void G__cpp_setup_memvarBaseCint() {
}
/***********************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
***********************************************************/

/*********************************************************
* Member function information setup for each class
*********************************************************/
static void G__setup_memfuncPMT(void) {
   /* PMT */
   G__tag_memfunc_setup(G__get_linked_tagnum(&G__BaseCintLN_PMT));
   G__tag_memfunc_reset();
}

static void G__setup_memfuncMSG(void) {
   /* MSG */
   G__tag_memfunc_setup(G__get_linked_tagnum(&G__BaseCintLN_MSG));
   G__tag_memfunc_reset();
}

static void G__setup_memfuncFORMAT(void) {
   /* FORMAT */
   G__tag_memfunc_setup(G__get_linked_tagnum(&G__BaseCintLN_FORMAT));
   G__tag_memfunc_reset();
}

static void G__setup_memfuncDATA_STRUCT(void) {
   /* DATA_STRUCT */
   G__tag_memfunc_setup(G__get_linked_tagnum(&G__BaseCintLN_DATA_STRUCT));
   G__tag_memfunc_reset();
}

static void G__setup_memfuncMessage(void) {
   /* Message */
   G__tag_memfunc_setup(G__get_linked_tagnum(&G__BaseCintLN_Message));
   G__memfunc_setup("Message",709,(G__InterfaceMethod) NULL, 105, G__get_linked_tagnum(&G__BaseCintLN_Message), -1, 0, 0, 1, 4, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("get",320,G__BaseCint_224_0_2, 85, G__get_linked_tagnum(&G__BaseCintLN_Message), -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("send",426,G__BaseCint_224_0_3, 121, -1, -1, 0, 2, 3, 1, 0, 
"i 'MSG::Level' - 0 - level u 'string' - 0 - msg", (char*)NULL, (void*) G__func2void( (void (*)(MSG::Level, string))(&Message::send) ), 0);
   G__memfunc_setup("send",426,G__BaseCint_224_0_4, 121, -1, -1, 0, 3, 3, 1, 0, 
"i 'MSG::Level' - 0 - level u 'string' - 0 - where "
"u 'string' - 0 - msg", (char*)NULL, (void*) G__func2void( (void (*)(MSG::Level, string, string))(&Message::send) ), 0);
   // automatic copy constructor
   G__memfunc_setup("Message", 709, G__BaseCint_224_0_5, (int) ('i'), G__get_linked_tagnum(&G__BaseCintLN_Message), -1, 0, 1, 1, 1, 0, "u 'Message' - 11 - -", (char*) NULL, (void*) NULL, 0);
   // automatic assignment operator
   G__memfunc_setup("operator=", 937, G__BaseCint_224_0_6, (int) ('u'), G__get_linked_tagnum(&G__BaseCintLN_Message), -1, 1, 1, 1, 1, 0, "u 'Message' - 11 - -", (char*) NULL, (void*) NULL, 0);
   G__tag_memfunc_reset();
}

static void G__setup_memfuncdecoder_base(void) {
   /* decoder_base */
   G__tag_memfunc_setup(G__get_linked_tagnum(&G__BaseCintLN_decoder_base));
   G__memfunc_setup("decoder_base",1232,G__BaseCint_225_0_1, 105, G__get_linked_tagnum(&G__BaseCintLN_decoder_base), -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("decoder_base",1232,G__BaseCint_225_0_2, 105, G__get_linked_tagnum(&G__BaseCintLN_decoder_base), -1, 0, 1, 1, 1, 0, "u 'decoder_base' - 11 - original", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("set_verbosity",1426,G__BaseCint_225_0_3, 121, -1, -1, 0, 1, 1, 1, 0, "i 'MSG::Level' - 0 - level", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("get_verbosity",1414,G__BaseCint_225_0_4, 105, G__get_linked_tagnum(&G__BaseCintLN_MSGcLcLLevel), -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("class_name",1046,G__BaseCint_225_0_5, 117, G__get_linked_tagnum(&G__BaseCintLN_string), -1, 0, 0, 1, 1, 9, "", (char*)NULL, (void*) NULL, 0);
   // automatic destructor
   G__memfunc_setup("~decoder_base", 1358, G__BaseCint_225_0_6, (int) ('y'), -1, -1, 0, 0, 1, 1, 0, "", (char*) NULL, (void*) NULL, 1);
   // automatic assignment operator
   G__memfunc_setup("operator=", 937, G__BaseCint_225_0_7, (int) ('u'), G__get_linked_tagnum(&G__BaseCintLN_decoder_base), -1, 1, 1, 1, 1, 0, "u 'decoder_base' - 11 - -", (char*) NULL, (void*) NULL, 0);
   G__tag_memfunc_reset();
}


/*********************************************************
* Member function information setup
*********************************************************/
extern "C" void G__cpp_setup_memfuncBaseCint() {
}

/*********************************************************
* Global variable information setup for each class
*********************************************************/
static void G__cpp_setup_global0() {

   /* Setting up global variables */
   G__resetplocal();

}

static void G__cpp_setup_global1() {
}

static void G__cpp_setup_global2() {

   G__resetglobalenv();
}
extern "C" void G__cpp_setup_globalBaseCint() {
  G__cpp_setup_global0();
  G__cpp_setup_global1();
  G__cpp_setup_global2();
}

/*********************************************************
* Global function information setup for each class
*********************************************************/
static void G__cpp_setup_func0() {
   G__lastifuncposition();

}

static void G__cpp_setup_func1() {
}

static void G__cpp_setup_func2() {
}

static void G__cpp_setup_func3() {
}

static void G__cpp_setup_func4() {
}

static void G__cpp_setup_func5() {
}

static void G__cpp_setup_func6() {
}

static void G__cpp_setup_func7() {
}

static void G__cpp_setup_func8() {
}

static void G__cpp_setup_func9() {
}

static void G__cpp_setup_func10() {
}

static void G__cpp_setup_func11() {
}

static void G__cpp_setup_func12() {
}

static void G__cpp_setup_func13() {

   G__resetifuncposition();
}

extern "C" void G__cpp_setup_funcBaseCint() {
  G__cpp_setup_func0();
  G__cpp_setup_func1();
  G__cpp_setup_func2();
  G__cpp_setup_func3();
  G__cpp_setup_func4();
  G__cpp_setup_func5();
  G__cpp_setup_func6();
  G__cpp_setup_func7();
  G__cpp_setup_func8();
  G__cpp_setup_func9();
  G__cpp_setup_func10();
  G__cpp_setup_func11();
  G__cpp_setup_func12();
  G__cpp_setup_func13();
}

/*********************************************************
* Class,struct,union,enum tag information setup
*********************************************************/
/* Setup class/struct taginfo */
G__linked_taginfo G__BaseCintLN_vectorlEunsignedsPshortcOallocatorlEunsignedsPshortgRsPgR = { "vector<unsigned short,allocator<unsigned short> >" , 99 , -1 };
G__linked_taginfo G__BaseCintLN_string = { "string" , 99 , -1 };
G__linked_taginfo G__BaseCintLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR = { "vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >" , 99 , -1 };
G__linked_taginfo G__BaseCintLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR = { "reverse_iterator<vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >::iterator>" , 99 , -1 };
G__linked_taginfo G__BaseCintLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR = { "vector<TVirtualArray*,allocator<TVirtualArray*> >" , 99 , -1 };
G__linked_taginfo G__BaseCintLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<TVirtualArray*,allocator<TVirtualArray*> >::iterator>" , 99 , -1 };
G__linked_taginfo G__BaseCintLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR = { "iterator<bidirectional_iterator_tag,TObject*,long,const TObject**,const TObject*&>" , 115 , -1 };
G__linked_taginfo G__BaseCintLN_PMT = { "PMT" , 110 , -1 };
G__linked_taginfo G__BaseCintLN_MSG = { "MSG" , 110 , -1 };
G__linked_taginfo G__BaseCintLN_MSGcLcLLevel = { "MSG::Level" , 101 , -1 };
G__linked_taginfo G__BaseCintLN_FORMAT = { "FORMAT" , 110 , -1 };
G__linked_taginfo G__BaseCintLN_FORMATcLcLINPUT_FILE = { "FORMAT::INPUT_FILE" , 101 , -1 };
G__linked_taginfo G__BaseCintLN_PMTcLcLDISCRIMINATOR = { "PMT::DISCRIMINATOR" , 101 , -1 };
G__linked_taginfo G__BaseCintLN_PMTcLcLPMT_WORD = { "PMT::PMT_WORD" , 101 , -1 };
G__linked_taginfo G__BaseCintLN_DATA_STRUCT = { "DATA_STRUCT" , 110 , -1 };
G__linked_taginfo G__BaseCintLN_DATA_STRUCTcLcLDATA_TYPE = { "DATA_STRUCT::DATA_TYPE" , 101 , -1 };
G__linked_taginfo G__BaseCintLN_Message = { "Message" , 99 , -1 };
G__linked_taginfo G__BaseCintLN_decoder_base = { "decoder_base" , 99 , -1 };

/* Reset class/struct taginfo */
extern "C" void G__cpp_reset_tagtableBaseCint() {
  G__BaseCintLN_vectorlEunsignedsPshortcOallocatorlEunsignedsPshortgRsPgR.tagnum = -1 ;
  G__BaseCintLN_string.tagnum = -1 ;
  G__BaseCintLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR.tagnum = -1 ;
  G__BaseCintLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__BaseCintLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR.tagnum = -1 ;
  G__BaseCintLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__BaseCintLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR.tagnum = -1 ;
  G__BaseCintLN_PMT.tagnum = -1 ;
  G__BaseCintLN_MSG.tagnum = -1 ;
  G__BaseCintLN_MSGcLcLLevel.tagnum = -1 ;
  G__BaseCintLN_FORMAT.tagnum = -1 ;
  G__BaseCintLN_FORMATcLcLINPUT_FILE.tagnum = -1 ;
  G__BaseCintLN_PMTcLcLDISCRIMINATOR.tagnum = -1 ;
  G__BaseCintLN_PMTcLcLPMT_WORD.tagnum = -1 ;
  G__BaseCintLN_DATA_STRUCT.tagnum = -1 ;
  G__BaseCintLN_DATA_STRUCTcLcLDATA_TYPE.tagnum = -1 ;
  G__BaseCintLN_Message.tagnum = -1 ;
  G__BaseCintLN_decoder_base.tagnum = -1 ;
}


extern "C" void G__cpp_setup_tagtableBaseCint() {

   /* Setting up class,struct,union tag entry */
   G__get_linked_tagnum_fwd(&G__BaseCintLN_vectorlEunsignedsPshortcOallocatorlEunsignedsPshortgRsPgR);
   G__get_linked_tagnum_fwd(&G__BaseCintLN_string);
   G__get_linked_tagnum_fwd(&G__BaseCintLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR);
   G__get_linked_tagnum_fwd(&G__BaseCintLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__BaseCintLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR);
   G__get_linked_tagnum_fwd(&G__BaseCintLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__BaseCintLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR);
   G__tagtable_setup(G__get_linked_tagnum_fwd(&G__BaseCintLN_PMT),0,-1,0,(char*)NULL,G__setup_memvarPMT,G__setup_memfuncPMT);
   G__tagtable_setup(G__get_linked_tagnum_fwd(&G__BaseCintLN_MSG),0,-1,0,(char*)NULL,G__setup_memvarMSG,G__setup_memfuncMSG);
   G__get_linked_tagnum_fwd(&G__BaseCintLN_MSGcLcLLevel);
   G__tagtable_setup(G__get_linked_tagnum_fwd(&G__BaseCintLN_FORMAT),0,-1,0,(char*)NULL,G__setup_memvarFORMAT,G__setup_memfuncFORMAT);
   G__get_linked_tagnum_fwd(&G__BaseCintLN_FORMATcLcLINPUT_FILE);
   G__get_linked_tagnum_fwd(&G__BaseCintLN_PMTcLcLDISCRIMINATOR);
   G__get_linked_tagnum_fwd(&G__BaseCintLN_PMTcLcLPMT_WORD);
   G__tagtable_setup(G__get_linked_tagnum_fwd(&G__BaseCintLN_DATA_STRUCT),0,-1,0,(char*)NULL,G__setup_memvarDATA_STRUCT,G__setup_memfuncDATA_STRUCT);
   G__get_linked_tagnum_fwd(&G__BaseCintLN_DATA_STRUCTcLcLDATA_TYPE);
   G__tagtable_setup(G__get_linked_tagnum_fwd(&G__BaseCintLN_Message),sizeof(Message),-1,263424,(char*)NULL,G__setup_memvarMessage,G__setup_memfuncMessage);
   G__tagtable_setup(G__get_linked_tagnum_fwd(&G__BaseCintLN_decoder_base),sizeof(decoder_base),-1,263936,(char*)NULL,G__setup_memvardecoder_base,G__setup_memfuncdecoder_base);
}
extern "C" void G__cpp_setupBaseCint(void) {
  G__check_setup_version(30051515,"G__cpp_setupBaseCint()");
  G__set_cpp_environmentBaseCint();
  G__cpp_setup_tagtableBaseCint();

  G__cpp_setup_inheritanceBaseCint();

  G__cpp_setup_typetableBaseCint();

  G__cpp_setup_memvarBaseCint();

  G__cpp_setup_memfuncBaseCint();
  G__cpp_setup_globalBaseCint();
  G__cpp_setup_funcBaseCint();

   if(0==G__getsizep2memfunc()) G__get_sizep2memfuncBaseCint();
  return;
}
class G__cpp_setup_initBaseCint {
  public:
    G__cpp_setup_initBaseCint() { G__add_setup_func("BaseCint",(G__incsetup)(&G__cpp_setupBaseCint)); G__call_setup_funcs(); }
   ~G__cpp_setup_initBaseCint() { G__remove_setup_func("BaseCint"); }
};
G__cpp_setup_initBaseCint G__cpp_setup_initializerBaseCint;

