//
// File generated by rootcint at Wed Nov 13 09:46:23 2013

// Do NOT change. Changes will be lost next time file is generated
//

#define R__DICTIONARY_FILENAME DecoderCint
#include "RConfig.h" //rootcint 4834
#if !defined(R__ACCESS_IN_SYMBOL)
//Break the privacy of classes -- Disabled for the moment
#define private public
#define protected public
#endif

// Since CINT ignores the std namespace, we need to do so in this file.
namespace std {} using namespace std;
#include "DecoderCint.h"

#include "TCollectionProxyInfo.h"
#include "TClass.h"
#include "TBuffer.h"
#include "TMemberInspector.h"
#include "TError.h"

#ifndef G__ROOT
#define G__ROOT
#endif

#include "RtypesImp.h"
#include "TIsAProxy.h"
#include "TFileMergeInfo.h"

// START OF SHADOWS

namespace ROOT {
   namespace Shadow {
      #if !(defined(R__ACCESS_IN_SYMBOL) || defined(R__USE_SHADOW_CLASS))
      typedef ::decoder_manager decoder_manager;
      #else
      class decoder_manager  :  public ::decoder_base {
         public:
         //friend XX;
         // To force the creation of a virtual table, throw just in case.
         virtual ~decoder_manager() throw() {};
         bool _debug_mode; ///< Debug mode boolean
         vector< ::ana_base* > _analyzers; ///< A collection of analyzers to be run
         string _input_file; ///< Input file name
         vector< ::string > _bin_files; //
         ::vector< ::string, allocator< ::string >  >::iterator _bin_file_iter; //
         ::bin_io_handler _fin; ///< Input file I/O handler
         bool _read_by_block; //
         unsigned long _read_block_size; //
         ::storage_manager* _storage; ///< Output file I/O handler
         ::algo_base* _decoder; ///< Decoding algorithm
      };
      #endif

      #if !(defined(R__ACCESS_IN_SYMBOL) || defined(R__USE_SHADOW_CLASS))
      typedef ::xmit_event_search xmit_event_search;
      #else
      class xmit_event_search  :  public ::decoder_base {
         public:
         //friend XX;
         // To force the creation of a virtual table, throw just in case.
         virtual ~xmit_event_search() throw() {};
         ::bin_io_handler _fin; //
         unsigned int _target_id; //
         bool _continue_mode; //
         bool _slow_readout; //
         bool _read_by_block; //
         unsigned long _index_event_id; //
         ::algo_base* _algo; //
      };
      #endif

   } // of namespace Shadow
} // of namespace ROOT
// END OF SHADOWS

namespace ROOT {
   void decoder_manager_ShowMembers(void *obj, TMemberInspector &R__insp);
   static void decoder_manager_Dictionary();
   static void *new_decoder_manager(void *p = 0);
   static void *newArray_decoder_manager(Long_t size, void *p);
   static void delete_decoder_manager(void *p);
   static void deleteArray_decoder_manager(void *p);
   static void destruct_decoder_manager(void *p);

   // Function generating the singleton type initializer
   static TGenericClassInfo *GenerateInitInstanceLocal(const ::decoder_manager*)
   {
      // Make sure the shadow class has the right sizeof
      R__ASSERT(sizeof(::decoder_manager) == sizeof(::ROOT::Shadow::decoder_manager));
      ::decoder_manager *ptr = 0;
      static ::TVirtualIsAProxy* isa_proxy = new ::TIsAProxy(typeid(::decoder_manager),0);
      static ::ROOT::TGenericClassInfo 
         instance("decoder_manager", "./decoder_manager.hh", 34,
                  typeid(::decoder_manager), DefineBehavior(ptr, ptr),
                  &decoder_manager_ShowMembers, &decoder_manager_Dictionary, isa_proxy, 4,
                  sizeof(::decoder_manager) );
      instance.SetNew(&new_decoder_manager);
      instance.SetNewArray(&newArray_decoder_manager);
      instance.SetDelete(&delete_decoder_manager);
      instance.SetDeleteArray(&deleteArray_decoder_manager);
      instance.SetDestructor(&destruct_decoder_manager);
      return &instance;
   }
   TGenericClassInfo *GenerateInitInstance(const ::decoder_manager*)
   {
      return GenerateInitInstanceLocal((::decoder_manager*)0);
   }
   // Static variable to force the class initialization
   static ::ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstanceLocal((const ::decoder_manager*)0x0); R__UseDummy(_R__UNIQUE_(Init));

   // Dictionary for non-ClassDef classes
   static void decoder_manager_Dictionary() {
      ::ROOT::GenerateInitInstanceLocal((const ::decoder_manager*)0x0)->GetClass();
   }

} // end of namespace ROOT

namespace ROOT {
   void xmit_event_search_ShowMembers(void *obj, TMemberInspector &R__insp);
   static void xmit_event_search_Dictionary();
   static void *new_xmit_event_search(void *p = 0);
   static void *newArray_xmit_event_search(Long_t size, void *p);
   static void delete_xmit_event_search(void *p);
   static void deleteArray_xmit_event_search(void *p);
   static void destruct_xmit_event_search(void *p);

   // Function generating the singleton type initializer
   static TGenericClassInfo *GenerateInitInstanceLocal(const ::xmit_event_search*)
   {
      // Make sure the shadow class has the right sizeof
      R__ASSERT(sizeof(::xmit_event_search) == sizeof(::ROOT::Shadow::xmit_event_search));
      ::xmit_event_search *ptr = 0;
      static ::TVirtualIsAProxy* isa_proxy = new ::TIsAProxy(typeid(::xmit_event_search),0);
      static ::ROOT::TGenericClassInfo 
         instance("xmit_event_search", "./xmit_event_search.hh", 8,
                  typeid(::xmit_event_search), DefineBehavior(ptr, ptr),
                  &xmit_event_search_ShowMembers, &xmit_event_search_Dictionary, isa_proxy, 4,
                  sizeof(::xmit_event_search) );
      instance.SetNew(&new_xmit_event_search);
      instance.SetNewArray(&newArray_xmit_event_search);
      instance.SetDelete(&delete_xmit_event_search);
      instance.SetDeleteArray(&deleteArray_xmit_event_search);
      instance.SetDestructor(&destruct_xmit_event_search);
      return &instance;
   }
   TGenericClassInfo *GenerateInitInstance(const ::xmit_event_search*)
   {
      return GenerateInitInstanceLocal((::xmit_event_search*)0);
   }
   // Static variable to force the class initialization
   static ::ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstanceLocal((const ::xmit_event_search*)0x0); R__UseDummy(_R__UNIQUE_(Init));

   // Dictionary for non-ClassDef classes
   static void xmit_event_search_Dictionary() {
      ::ROOT::GenerateInitInstanceLocal((const ::xmit_event_search*)0x0)->GetClass();
   }

} // end of namespace ROOT

//______________________________________________________________________________
namespace ROOT {
   void decoder_manager_ShowMembers(void *obj, TMemberInspector &R__insp)
   {
      // Inspect the data members of an object of class decoder_manager.
      typedef ::ROOT::Shadow::decoder_manager ShadowClass;
      ShadowClass *sobj = (ShadowClass*)obj;
      if (sobj) { } // Dummy usage just in case there is no datamember.

      TClass *R__cl  = ::ROOT::GenerateInitInstanceLocal((const ::decoder_manager*)0x0)->GetClass();
      if (R__cl || R__insp.IsA()) { }
      R__insp.Inspect(R__cl, R__insp.GetParent(), "_debug_mode", &sobj->_debug_mode);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "_analyzers", (void*)&sobj->_analyzers);
      R__insp.InspectMember("vector<ana_base*>", (void*)&sobj->_analyzers, "_analyzers.", false);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "_input_file", (void*)&sobj->_input_file);
      R__insp.InspectMember("string", (void*)&sobj->_input_file, "_input_file.", false);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "_bin_files", (void*)&sobj->_bin_files);
      R__insp.InspectMember("vector<std::string>", (void*)&sobj->_bin_files, "_bin_files.", false);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "_bin_file_iter", (void*)&sobj->_bin_file_iter);
      R__insp.InspectMember("vector<string,allocator<string> >::iterator", (void*)&sobj->_bin_file_iter, "_bin_file_iter.", false);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "_fin", (void*)&sobj->_fin);
      R__insp.InspectMember("bin_io_handler", (void*)&sobj->_fin, "_fin.", false);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "_read_by_block", &sobj->_read_by_block);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "_read_block_size", &sobj->_read_block_size);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*_storage", &sobj->_storage);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*_decoder", &sobj->_decoder);
      R__insp.GenericShowMembers("decoder_base", ( ::decoder_base * )( (::decoder_manager*) obj ), false);
   }

}

namespace ROOT {
   // Wrappers around operator new
   static void *new_decoder_manager(void *p) {
      return  p ? ::new((::ROOT::TOperatorNewHelper*)p) ::decoder_manager : new ::decoder_manager;
   }
   static void *newArray_decoder_manager(Long_t nElements, void *p) {
      return p ? ::new((::ROOT::TOperatorNewHelper*)p) ::decoder_manager[nElements] : new ::decoder_manager[nElements];
   }
   // Wrapper around operator delete
   static void delete_decoder_manager(void *p) {
      delete ((::decoder_manager*)p);
   }
   static void deleteArray_decoder_manager(void *p) {
      delete [] ((::decoder_manager*)p);
   }
   static void destruct_decoder_manager(void *p) {
      typedef ::decoder_manager current_t;
      ((current_t*)p)->~current_t();
   }
} // end of namespace ROOT for class ::decoder_manager

//______________________________________________________________________________
namespace ROOT {
   void xmit_event_search_ShowMembers(void *obj, TMemberInspector &R__insp)
   {
      // Inspect the data members of an object of class xmit_event_search.
      typedef ::ROOT::Shadow::xmit_event_search ShadowClass;
      ShadowClass *sobj = (ShadowClass*)obj;
      if (sobj) { } // Dummy usage just in case there is no datamember.

      TClass *R__cl  = ::ROOT::GenerateInitInstanceLocal((const ::xmit_event_search*)0x0)->GetClass();
      if (R__cl || R__insp.IsA()) { }
      R__insp.Inspect(R__cl, R__insp.GetParent(), "_fin", (void*)&sobj->_fin);
      R__insp.InspectMember("bin_io_handler", (void*)&sobj->_fin, "_fin.", false);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "_target_id", &sobj->_target_id);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "_continue_mode", &sobj->_continue_mode);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "_slow_readout", &sobj->_slow_readout);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "_read_by_block", &sobj->_read_by_block);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "_index_event_id", &sobj->_index_event_id);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*_algo", &sobj->_algo);
      R__insp.GenericShowMembers("decoder_base", ( ::decoder_base * )( (::xmit_event_search*) obj ), false);
   }

}

namespace ROOT {
   // Wrappers around operator new
   static void *new_xmit_event_search(void *p) {
      return  p ? ::new((::ROOT::TOperatorNewHelper*)p) ::xmit_event_search : new ::xmit_event_search;
   }
   static void *newArray_xmit_event_search(Long_t nElements, void *p) {
      return p ? ::new((::ROOT::TOperatorNewHelper*)p) ::xmit_event_search[nElements] : new ::xmit_event_search[nElements];
   }
   // Wrapper around operator delete
   static void delete_xmit_event_search(void *p) {
      delete ((::xmit_event_search*)p);
   }
   static void deleteArray_xmit_event_search(void *p) {
      delete [] ((::xmit_event_search*)p);
   }
   static void destruct_xmit_event_search(void *p) {
      typedef ::xmit_event_search current_t;
      ((current_t*)p)->~current_t();
   }
} // end of namespace ROOT for class ::xmit_event_search

namespace ROOT {
   void vectorlEana_basemUgR_ShowMembers(void *obj, TMemberInspector &R__insp);
   static void vectorlEana_basemUgR_Dictionary();
   static void *new_vectorlEana_basemUgR(void *p = 0);
   static void *newArray_vectorlEana_basemUgR(Long_t size, void *p);
   static void delete_vectorlEana_basemUgR(void *p);
   static void deleteArray_vectorlEana_basemUgR(void *p);
   static void destruct_vectorlEana_basemUgR(void *p);

   // Function generating the singleton type initializer
   static TGenericClassInfo *GenerateInitInstanceLocal(const vector<ana_base*>*)
   {
      vector<ana_base*> *ptr = 0;
      static ::TVirtualIsAProxy* isa_proxy = new ::TIsAProxy(typeid(vector<ana_base*>),0);
      static ::ROOT::TGenericClassInfo 
         instance("vector<ana_base*>", -2, "prec_stl/vector", 49,
                  typeid(vector<ana_base*>), DefineBehavior(ptr, ptr),
                  0, &vectorlEana_basemUgR_Dictionary, isa_proxy, 0,
                  sizeof(vector<ana_base*>) );
      instance.SetNew(&new_vectorlEana_basemUgR);
      instance.SetNewArray(&newArray_vectorlEana_basemUgR);
      instance.SetDelete(&delete_vectorlEana_basemUgR);
      instance.SetDeleteArray(&deleteArray_vectorlEana_basemUgR);
      instance.SetDestructor(&destruct_vectorlEana_basemUgR);
      instance.AdoptCollectionProxyInfo(TCollectionProxyInfo::Generate(TCollectionProxyInfo::Pushback< vector<ana_base*> >()));
      return &instance;
   }
   // Static variable to force the class initialization
   static ::ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstanceLocal((const vector<ana_base*>*)0x0); R__UseDummy(_R__UNIQUE_(Init));

   // Dictionary for non-ClassDef classes
   static void vectorlEana_basemUgR_Dictionary() {
      ::ROOT::GenerateInitInstanceLocal((const vector<ana_base*>*)0x0)->GetClass();
   }

} // end of namespace ROOT

namespace ROOT {
   // Wrappers around operator new
   static void *new_vectorlEana_basemUgR(void *p) {
      return  p ? ::new((::ROOT::TOperatorNewHelper*)p) vector<ana_base*> : new vector<ana_base*>;
   }
   static void *newArray_vectorlEana_basemUgR(Long_t nElements, void *p) {
      return p ? ::new((::ROOT::TOperatorNewHelper*)p) vector<ana_base*>[nElements] : new vector<ana_base*>[nElements];
   }
   // Wrapper around operator delete
   static void delete_vectorlEana_basemUgR(void *p) {
      delete ((vector<ana_base*>*)p);
   }
   static void deleteArray_vectorlEana_basemUgR(void *p) {
      delete [] ((vector<ana_base*>*)p);
   }
   static void destruct_vectorlEana_basemUgR(void *p) {
      typedef vector<ana_base*> current_t;
      ((current_t*)p)->~current_t();
   }
} // end of namespace ROOT for class vector<ana_base*>

namespace ROOT {
   void vectorlEstringgR_ShowMembers(void *obj, TMemberInspector &R__insp);
   static void vectorlEstringgR_Dictionary();
   static void *new_vectorlEstringgR(void *p = 0);
   static void *newArray_vectorlEstringgR(Long_t size, void *p);
   static void delete_vectorlEstringgR(void *p);
   static void deleteArray_vectorlEstringgR(void *p);
   static void destruct_vectorlEstringgR(void *p);

   // Function generating the singleton type initializer
   static TGenericClassInfo *GenerateInitInstanceLocal(const vector<string>*)
   {
      vector<string> *ptr = 0;
      static ::TVirtualIsAProxy* isa_proxy = new ::TIsAProxy(typeid(vector<string>),0);
      static ::ROOT::TGenericClassInfo 
         instance("vector<string>", -2, "prec_stl/vector", 49,
                  typeid(vector<string>), DefineBehavior(ptr, ptr),
                  0, &vectorlEstringgR_Dictionary, isa_proxy, 0,
                  sizeof(vector<string>) );
      instance.SetNew(&new_vectorlEstringgR);
      instance.SetNewArray(&newArray_vectorlEstringgR);
      instance.SetDelete(&delete_vectorlEstringgR);
      instance.SetDeleteArray(&deleteArray_vectorlEstringgR);
      instance.SetDestructor(&destruct_vectorlEstringgR);
      instance.AdoptCollectionProxyInfo(TCollectionProxyInfo::Generate(TCollectionProxyInfo::Pushback< vector<string> >()));
      return &instance;
   }
   // Static variable to force the class initialization
   static ::ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstanceLocal((const vector<string>*)0x0); R__UseDummy(_R__UNIQUE_(Init));

   // Dictionary for non-ClassDef classes
   static void vectorlEstringgR_Dictionary() {
      ::ROOT::GenerateInitInstanceLocal((const vector<string>*)0x0)->GetClass();
   }

} // end of namespace ROOT

namespace ROOT {
   // Wrappers around operator new
   static void *new_vectorlEstringgR(void *p) {
      return  p ? ::new((::ROOT::TOperatorNewHelper*)p) vector<string> : new vector<string>;
   }
   static void *newArray_vectorlEstringgR(Long_t nElements, void *p) {
      return p ? ::new((::ROOT::TOperatorNewHelper*)p) vector<string>[nElements] : new vector<string>[nElements];
   }
   // Wrapper around operator delete
   static void delete_vectorlEstringgR(void *p) {
      delete ((vector<string>*)p);
   }
   static void deleteArray_vectorlEstringgR(void *p) {
      delete [] ((vector<string>*)p);
   }
   static void destruct_vectorlEstringgR(void *p) {
      typedef vector<string> current_t;
      ((current_t*)p)->~current_t();
   }
} // end of namespace ROOT for class vector<string>

/********************************************************
* DecoderCint.cc
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************/

#ifdef G__MEMTEST
#undef malloc
#undef free
#endif

#if defined(__GNUC__) && __GNUC__ >= 4 && ((__GNUC_MINOR__ == 2 && __GNUC_PATCHLEVEL__ >= 1) || (__GNUC_MINOR__ >= 3))
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif

extern "C" void G__cpp_reset_tagtableDecoderCint();

extern "C" void G__set_cpp_environmentDecoderCint() {
  G__add_compiledheader("TObject.h");
  G__add_compiledheader("TMemberInspector.h");
  G__add_compiledheader("Decoder-TypeDef.hh");
  G__add_compiledheader("decoder_manager.hh");
  G__add_compiledheader("xmit_event_search.hh");
  G__cpp_reset_tagtableDecoderCint();
}
#include <new>
extern "C" int G__cpp_dllrevDecoderCint() { return(30051515); }

/*********************************************************
* Member function Interface Method
*********************************************************/

/* decoder_manager */
static int G__DecoderCint_713_0_1(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   decoder_manager* p = NULL;
   char* gvp = (char*) G__getgvp();
   int n = G__getaryconstruct();
   if (n) {
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new decoder_manager[n];
     } else {
       p = new((void*) gvp) decoder_manager[n];
     }
   } else {
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new decoder_manager;
     } else {
       p = new((void*) gvp) decoder_manager;
     }
   }
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__DecoderCintLN_decoder_manager));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__DecoderCint_713_0_2(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((decoder_manager*) G__getstructoffset())->add_input_filename(*((string*) G__int(libp->para[0])));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__DecoderCint_713_0_3(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((decoder_manager*) G__getstructoffset())->set_output_filename(*((string*) G__int(libp->para[0])));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__DecoderCint_713_0_4(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   switch (libp->paran) {
   case 2:
      ((decoder_manager*) G__getstructoffset())->set_data_to_write((DATA_STRUCT::DATA_TYPE) G__int(libp->para[0]), (bool) G__int(libp->para[1]));
      G__setnull(result7);
      break;
   case 1:
      ((decoder_manager*) G__getstructoffset())->set_data_to_write((DATA_STRUCT::DATA_TYPE) G__int(libp->para[0]));
      G__setnull(result7);
      break;
   }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__DecoderCint_713_0_5(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((decoder_manager*) G__getstructoffset())->set_format((FORMAT::INPUT_FILE) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__DecoderCint_713_0_6(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((decoder_manager*) G__getstructoffset())->set_decoder((algo_base*) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__DecoderCint_713_0_7(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((decoder_manager*) G__getstructoffset())->debug_mode((bool) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__DecoderCint_713_0_8(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 103, (long) ((decoder_manager*) G__getstructoffset())->run());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__DecoderCint_713_0_9(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((decoder_manager*) G__getstructoffset())->reset();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__DecoderCint_713_0_10(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   switch (libp->paran) {
   case 1:
      ((decoder_manager*) G__getstructoffset())->set_read_by_block((bool) G__int(libp->para[0]));
      G__setnull(result7);
      break;
   case 0:
      ((decoder_manager*) G__getstructoffset())->set_read_by_block();
      G__setnull(result7);
      break;
   }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__DecoderCint_713_0_11(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((decoder_manager*) G__getstructoffset())->set_read_block_size((size_t) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic copy constructor
static int G__DecoderCint_713_0_16(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)

{
   decoder_manager* p;
   void* tmp = (void*) G__int(libp->para[0]);
   p = new decoder_manager(*(decoder_manager*) tmp);
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__DecoderCintLN_decoder_manager));
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic destructor
typedef decoder_manager G__Tdecoder_manager;
static int G__DecoderCint_713_0_17(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   char* gvp = (char*) G__getgvp();
   long soff = G__getstructoffset();
   int n = G__getaryconstruct();
   //
   //has_a_delete: 0
   //has_own_delete1arg: 0
   //has_own_delete2arg: 0
   //
   if (!soff) {
     return(1);
   }
   if (n) {
     if (gvp == (char*)G__PVOID) {
       delete[] (decoder_manager*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       for (int i = n - 1; i >= 0; --i) {
         ((decoder_manager*) (soff+(sizeof(decoder_manager)*i)))->~G__Tdecoder_manager();
       }
       G__setgvp((long)gvp);
     }
   } else {
     if (gvp == (char*)G__PVOID) {
       delete (decoder_manager*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       ((decoder_manager*) (soff))->~G__Tdecoder_manager();
       G__setgvp((long)gvp);
     }
   }
   G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic assignment operator
static int G__DecoderCint_713_0_18(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   decoder_manager* dest = (decoder_manager*) G__getstructoffset();
   *dest = *(decoder_manager*) libp->para[0].ref;
   const decoder_manager& obj = *dest;
   result7->ref = (long) (&obj);
   result7->obj.i = (long) (&obj);
   return(1 || funcname || hash || result7 || libp) ;
}


/* xmit_event_search */
static int G__DecoderCint_728_0_1(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   xmit_event_search* p = NULL;
   char* gvp = (char*) G__getgvp();
   int n = G__getaryconstruct();
   if (n) {
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new xmit_event_search[n];
     } else {
       p = new((void*) gvp) xmit_event_search[n];
     }
   } else {
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new xmit_event_search;
     } else {
       p = new((void*) gvp) xmit_event_search;
     }
   }
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__DecoderCintLN_xmit_event_search));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__DecoderCint_728_0_2(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((xmit_event_search*) G__getstructoffset())->set_target_id((PMT::word_t) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__DecoderCint_728_0_3(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((xmit_event_search*) G__getstructoffset())->set_filename(*((string*) G__int(libp->para[0])));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__DecoderCint_728_0_4(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((xmit_event_search*) G__getstructoffset())->set_continue_mode((bool) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__DecoderCint_728_0_5(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((xmit_event_search*) G__getstructoffset())->set_format((FORMAT::INPUT_FILE) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__DecoderCint_728_0_6(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   switch (libp->paran) {
   case 1:
      ((xmit_event_search*) G__getstructoffset())->set_slow_readout((bool) G__int(libp->para[0]));
      G__setnull(result7);
      break;
   case 0:
      ((xmit_event_search*) G__getstructoffset())->set_slow_readout();
      G__setnull(result7);
      break;
   }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__DecoderCint_728_0_7(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((xmit_event_search*) G__getstructoffset())->set_read_by_block((bool) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__DecoderCint_728_0_8(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 103, (long) ((xmit_event_search*) G__getstructoffset())->run());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__DecoderCint_728_0_9(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((xmit_event_search*) G__getstructoffset())->print_word((vector<PMT::word_t>*) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__DecoderCint_728_0_10(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 103, (long) ((const xmit_event_search*) G__getstructoffset())->new_event((PMT::word_t) G__int(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic copy constructor
static int G__DecoderCint_728_0_11(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)

{
   xmit_event_search* p;
   void* tmp = (void*) G__int(libp->para[0]);
   p = new xmit_event_search(*(xmit_event_search*) tmp);
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__DecoderCintLN_xmit_event_search));
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic destructor
typedef xmit_event_search G__Txmit_event_search;
static int G__DecoderCint_728_0_12(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   char* gvp = (char*) G__getgvp();
   long soff = G__getstructoffset();
   int n = G__getaryconstruct();
   //
   //has_a_delete: 0
   //has_own_delete1arg: 0
   //has_own_delete2arg: 0
   //
   if (!soff) {
     return(1);
   }
   if (n) {
     if (gvp == (char*)G__PVOID) {
       delete[] (xmit_event_search*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       for (int i = n - 1; i >= 0; --i) {
         ((xmit_event_search*) (soff+(sizeof(xmit_event_search)*i)))->~G__Txmit_event_search();
       }
       G__setgvp((long)gvp);
     }
   } else {
     if (gvp == (char*)G__PVOID) {
       delete (xmit_event_search*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       ((xmit_event_search*) (soff))->~G__Txmit_event_search();
       G__setgvp((long)gvp);
     }
   }
   G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic assignment operator
static int G__DecoderCint_728_0_13(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   xmit_event_search* dest = (xmit_event_search*) G__getstructoffset();
   *dest = *(xmit_event_search*) libp->para[0].ref;
   const xmit_event_search& obj = *dest;
   result7->ref = (long) (&obj);
   result7->obj.i = (long) (&obj);
   return(1 || funcname || hash || result7 || libp) ;
}


/* Setting up global function */

/*********************************************************
* Member function Stub
*********************************************************/

/* decoder_manager */

/* xmit_event_search */

/*********************************************************
* Global function Stub
*********************************************************/

/*********************************************************
* Get size of pointer to member function
*********************************************************/
class G__Sizep2memfuncDecoderCint {
 public:
  G__Sizep2memfuncDecoderCint(): p(&G__Sizep2memfuncDecoderCint::sizep2memfunc) {}
    size_t sizep2memfunc() { return(sizeof(p)); }
  private:
    size_t (G__Sizep2memfuncDecoderCint::*p)();
};

size_t G__get_sizep2memfuncDecoderCint()
{
  G__Sizep2memfuncDecoderCint a;
  G__setsizep2memfunc((int)a.sizep2memfunc());
  return((size_t)a.sizep2memfunc());
}


/*********************************************************
* virtual base class offset calculation interface
*********************************************************/

   /* Setting up class inheritance */

/*********************************************************
* Inheritance information setup/
*********************************************************/
extern "C" void G__cpp_setup_inheritanceDecoderCint() {

   /* Setting up class inheritance */
   if(0==G__getnumbaseclass(G__get_linked_tagnum(&G__DecoderCintLN_decoder_manager))) {
     decoder_manager *G__Lderived;
     G__Lderived=(decoder_manager*)0x1000;
     {
       decoder_base *G__Lpbase=(decoder_base*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__DecoderCintLN_decoder_manager),G__get_linked_tagnum(&G__DecoderCintLN_decoder_base),(long)G__Lpbase-(long)G__Lderived,1,1);
     }
   }
   if(0==G__getnumbaseclass(G__get_linked_tagnum(&G__DecoderCintLN_xmit_event_search))) {
     xmit_event_search *G__Lderived;
     G__Lderived=(xmit_event_search*)0x1000;
     {
       decoder_base *G__Lpbase=(decoder_base*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__DecoderCintLN_xmit_event_search),G__get_linked_tagnum(&G__DecoderCintLN_decoder_base),(long)G__Lpbase-(long)G__Lderived,1,1);
     }
   }
}

/*********************************************************
* typedef information setup/
*********************************************************/
extern "C" void G__cpp_setup_typetableDecoderCint() {

   /* Setting up typedef entry */
   G__search_typename2("vector<ROOT::TSchemaHelper>",117,G__get_linked_tagnum(&G__DecoderCintLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__DecoderCintLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__DecoderCintLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__DecoderCintLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__DecoderCintLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<TVirtualArray*>",117,G__get_linked_tagnum(&G__DecoderCintLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__DecoderCintLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__DecoderCintLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__DecoderCintLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__DecoderCintLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<std::bidirectional_iterator_tag,TObject*,std::ptrdiff_t,const TObject**,const TObject*&>",117,G__get_linked_tagnum(&G__DecoderCintLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*,std::ptrdiff_t,const TObject**,const TObject*&>",117,G__get_linked_tagnum(&G__DecoderCintLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*>",117,G__get_linked_tagnum(&G__DecoderCintLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*,long>",117,G__get_linked_tagnum(&G__DecoderCintLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*,long,const TObject**>",117,G__get_linked_tagnum(&G__DecoderCintLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<std::string,TObjArray*>",117,G__get_linked_tagnum(&G__DecoderCintLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<string,TObjArray*>",117,G__get_linked_tagnum(&G__DecoderCintLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<string,TObjArray*>",117,G__get_linked_tagnum(&G__DecoderCintLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<string,TObjArray*,less<string> >",117,G__get_linked_tagnum(&G__DecoderCintLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<pulse_info>",117,G__get_linked_tagnum(&G__DecoderCintLN_vectorlEpulse_infocOallocatorlEpulse_infogRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__DecoderCintLN_reverse_iteratorlEvectorlEpulse_infocOallocatorlEpulse_infogRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__DecoderCintLN_vectorlEpulse_infocOallocatorlEpulse_infogRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__DecoderCintLN_reverse_iteratorlEvectorlEpulse_infocOallocatorlEpulse_infogRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__DecoderCintLN_vectorlEpulse_infocOallocatorlEpulse_infogRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<int>",117,G__get_linked_tagnum(&G__DecoderCintLN_vectorlEintcOallocatorlEintgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__DecoderCintLN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__DecoderCintLN_vectorlEintcOallocatorlEintgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__DecoderCintLN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__DecoderCintLN_vectorlEintcOallocatorlEintgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<std::string>",117,G__get_linked_tagnum(&G__DecoderCintLN_vectorlEstringcOallocatorlEstringgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<string>",117,G__get_linked_tagnum(&G__DecoderCintLN_vectorlEstringcOallocatorlEstringgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__DecoderCintLN_reverse_iteratorlEvectorlEstringcOallocatorlEstringgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__DecoderCintLN_vectorlEstringcOallocatorlEstringgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__DecoderCintLN_reverse_iteratorlEvectorlEstringcOallocatorlEstringgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__DecoderCintLN_vectorlEstringcOallocatorlEstringgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<string>",117,G__get_linked_tagnum(&G__DecoderCintLN_vectorlEstringcOallocatorlEstringgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<std::string,double>",117,G__get_linked_tagnum(&G__DecoderCintLN_maplEstringcOdoublecOlesslEstringgRcOallocatorlEpairlEconstsPstringcOdoublegRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<string,double>",117,G__get_linked_tagnum(&G__DecoderCintLN_maplEstringcOdoublecOlesslEstringgRcOallocatorlEpairlEconstsPstringcOdoublegRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<std::string,int>",117,G__get_linked_tagnum(&G__DecoderCintLN_maplEstringcOintcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOintgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<string,int>",117,G__get_linked_tagnum(&G__DecoderCintLN_maplEstringcOintcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOintgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<std::string,std::string>",117,G__get_linked_tagnum(&G__DecoderCintLN_maplEstringcOstringcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOstringgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<string,std::string>",117,G__get_linked_tagnum(&G__DecoderCintLN_maplEstringcOstringcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOstringgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<string,string>",117,G__get_linked_tagnum(&G__DecoderCintLN_maplEstringcOstringcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOstringgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<string,string,less<string> >",117,G__get_linked_tagnum(&G__DecoderCintLN_maplEstringcOstringcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOstringgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<std::string,bool>",117,G__get_linked_tagnum(&G__DecoderCintLN_maplEstringcOboolcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOboolgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<string,bool>",117,G__get_linked_tagnum(&G__DecoderCintLN_maplEstringcOboolcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOboolgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<string,bool>",117,G__get_linked_tagnum(&G__DecoderCintLN_maplEstringcOboolcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOboolgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<string,bool,less<string> >",117,G__get_linked_tagnum(&G__DecoderCintLN_maplEstringcOboolcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOboolgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<std::string,std::vector<double> >",117,G__get_linked_tagnum(&G__DecoderCintLN_maplEstringcOvectorlEdoublecOallocatorlEdoublegRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlEdoublecOallocatorlEdoublegRsPgRsPgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<string,std::vector<double> >",117,G__get_linked_tagnum(&G__DecoderCintLN_maplEstringcOvectorlEdoublecOallocatorlEdoublegRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlEdoublecOallocatorlEdoublegRsPgRsPgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<string,vector<double,allocator<double> > >",117,G__get_linked_tagnum(&G__DecoderCintLN_maplEstringcOvectorlEdoublecOallocatorlEdoublegRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlEdoublecOallocatorlEdoublegRsPgRsPgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<string,vector<double,allocator<double> >,less<string> >",117,G__get_linked_tagnum(&G__DecoderCintLN_maplEstringcOvectorlEdoublecOallocatorlEdoublegRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlEdoublecOallocatorlEdoublegRsPgRsPgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<std::string,std::vector<int> >",117,G__get_linked_tagnum(&G__DecoderCintLN_maplEstringcOvectorlEintcOallocatorlEintgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlEintcOallocatorlEintgRsPgRsPgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<string,std::vector<int> >",117,G__get_linked_tagnum(&G__DecoderCintLN_maplEstringcOvectorlEintcOallocatorlEintgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlEintcOallocatorlEintgRsPgRsPgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<string,vector<int,allocator<int> > >",117,G__get_linked_tagnum(&G__DecoderCintLN_maplEstringcOvectorlEintcOallocatorlEintgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlEintcOallocatorlEintgRsPgRsPgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<string,vector<int,allocator<int> >,less<string> >",117,G__get_linked_tagnum(&G__DecoderCintLN_maplEstringcOvectorlEintcOallocatorlEintgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlEintcOallocatorlEintgRsPgRsPgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<std::string,std::vector<std::string> >",117,G__get_linked_tagnum(&G__DecoderCintLN_maplEstringcOvectorlEstringcOallocatorlEstringgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlEstringcOallocatorlEstringgRsPgRsPgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<string,std::vector<string> >",117,G__get_linked_tagnum(&G__DecoderCintLN_maplEstringcOvectorlEstringcOallocatorlEstringgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlEstringcOallocatorlEstringgRsPgRsPgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<string,vector<string,allocator<string> > >",117,G__get_linked_tagnum(&G__DecoderCintLN_maplEstringcOvectorlEstringcOallocatorlEstringgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlEstringcOallocatorlEstringgRsPgRsPgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<string,vector<string,allocator<string> >,less<string> >",117,G__get_linked_tagnum(&G__DecoderCintLN_maplEstringcOvectorlEstringcOallocatorlEstringgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlEstringcOallocatorlEstringgRsPgRsPgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<std::string,std::vector<bool> >",117,G__get_linked_tagnum(&G__DecoderCintLN_maplEstringcOvectorlEboolcOallocatorlEboolgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlEboolcOallocatorlEboolgRsPgRsPgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<string,std::vector<bool> >",117,G__get_linked_tagnum(&G__DecoderCintLN_maplEstringcOvectorlEboolcOallocatorlEboolgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlEboolcOallocatorlEboolgRsPgRsPgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<string,vector<bool,allocator<bool> > >",117,G__get_linked_tagnum(&G__DecoderCintLN_maplEstringcOvectorlEboolcOallocatorlEboolgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlEboolcOallocatorlEboolgRsPgRsPgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<string,vector<bool,allocator<bool> >,less<string> >",117,G__get_linked_tagnum(&G__DecoderCintLN_maplEstringcOvectorlEboolcOallocatorlEboolgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlEboolcOallocatorlEboolgRsPgRsPgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<user_info>",117,G__get_linked_tagnum(&G__DecoderCintLN_vectorlEuser_infocOallocatorlEuser_infogRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__DecoderCintLN_reverse_iteratorlEvectorlEuser_infocOallocatorlEuser_infogRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__DecoderCintLN_vectorlEuser_infocOallocatorlEuser_infogRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__DecoderCintLN_reverse_iteratorlEvectorlEuser_infocOallocatorlEuser_infogRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__DecoderCintLN_vectorlEuser_infocOallocatorlEuser_infogRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<PMT::ch_adc_t>",117,G__get_linked_tagnum(&G__DecoderCintLN_vectorlEunsignedsPshortcOallocatorlEunsignedsPshortgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<pmt_waveform>",117,G__get_linked_tagnum(&G__DecoderCintLN_vectorlEpmt_waveformcOallocatorlEpmt_waveformgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__DecoderCintLN_reverse_iteratorlEvectorlEpmt_waveformcOallocatorlEpmt_waveformgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__DecoderCintLN_vectorlEpmt_waveformcOallocatorlEpmt_waveformgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__DecoderCintLN_reverse_iteratorlEvectorlEpmt_waveformcOallocatorlEpmt_waveformgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__DecoderCintLN_vectorlEpmt_waveformcOallocatorlEpmt_waveformgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<tpc_waveform>",117,G__get_linked_tagnum(&G__DecoderCintLN_vectorlEtpc_waveformcOallocatorlEtpc_waveformgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__DecoderCintLN_reverse_iteratorlEvectorlEtpc_waveformcOallocatorlEtpc_waveformgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__DecoderCintLN_vectorlEtpc_waveformcOallocatorlEtpc_waveformgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__DecoderCintLN_reverse_iteratorlEvectorlEtpc_waveformcOallocatorlEtpc_waveformgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__DecoderCintLN_vectorlEtpc_waveformcOallocatorlEtpc_waveformgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<PMT::word_t>",117,G__get_linked_tagnum(&G__DecoderCintLN_vectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("deque<PMT::word_t>",117,G__get_linked_tagnum(&G__DecoderCintLN_dequelEunsignedsPintcOallocatorlEunsignedsPintgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("deque<unsigned int>",117,G__get_linked_tagnum(&G__DecoderCintLN_dequelEunsignedsPintcOallocatorlEunsignedsPintgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<ana_base*>",117,G__get_linked_tagnum(&G__DecoderCintLN_vectorlEana_basemUcOallocatorlEana_basemUgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__DecoderCintLN_reverse_iteratorlEvectorlEana_basemUcOallocatorlEana_basemUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__DecoderCintLN_vectorlEana_basemUcOallocatorlEana_basemUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__DecoderCintLN_reverse_iteratorlEvectorlEana_basemUcOallocatorlEana_basemUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__DecoderCintLN_vectorlEana_basemUcOallocatorlEana_basemUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<UShort_t>",117,G__get_linked_tagnum(&G__DecoderCintLN_vectorlEunsignedsPshortcOallocatorlEunsignedsPshortgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
}

/*********************************************************
* Data Member information setup/
*********************************************************/

   /* Setting up class,struct,union tag member variable */

   /* decoder_manager */
static void G__setup_memvardecoder_manager(void) {
   G__tag_memvar_setup(G__get_linked_tagnum(&G__DecoderCintLN_decoder_manager));
   { decoder_manager *p; p=(decoder_manager*)0x1000; if (p) { }
   G__memvar_setup((void*)0,103,0,0,-1,-1,-1,4,"_debug_mode=",0,"/< Debug mode boolean");
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__DecoderCintLN_vectorlEana_basemUcOallocatorlEana_basemUgRsPgR),G__defined_typename("vector<ana_base*>"),-1,4,"_analyzers=",0,"/< A collection of analyzers to be run");
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__DecoderCintLN_string),-1,-1,4,"_input_file=",0,"/< Input file name");
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__DecoderCintLN_vectorlEstringcOallocatorlEstringgRsPgR),G__defined_typename("vector<std::string>"),-1,4,"_bin_files=",0,(char*)NULL);
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__DecoderCintLN_vectorlEstringcOallocatorlEstringgRsPgRcLcLiterator),-1,-1,4,"_bin_file_iter=",0,(char*)NULL);
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__DecoderCintLN_bin_io_handler),-1,-1,4,"_fin=",0,"/< Input file I/O handler");
   G__memvar_setup((void*)0,103,0,0,-1,-1,-1,4,"_read_by_block=",0,(char*)NULL);
   G__memvar_setup((void*)0,107,0,0,-1,G__defined_typename("size_t"),-1,4,"_read_block_size=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__DecoderCintLN_storage_manager),-1,-1,4,"_storage=",0,"/< Output file I/O handler");
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__DecoderCintLN_algo_base),-1,-1,4,"_decoder=",0,"/< Decoding algorithm");
   }
   G__tag_memvar_reset();
}


   /* xmit_event_search */
static void G__setup_memvarxmit_event_search(void) {
   G__tag_memvar_setup(G__get_linked_tagnum(&G__DecoderCintLN_xmit_event_search));
   { xmit_event_search *p; p=(xmit_event_search*)0x1000; if (p) { }
   G__memvar_setup((void*)G__PVOID,107,0,1,-1,G__defined_typename("size_t"),-2,1,G__FastAllocString(2048).Format("XMIT_INDEX_EVENT_ID=%lluULL",(unsigned long long)xmit_event_search::XMIT_INDEX_EVENT_ID).data(),0,(char*)NULL);
   G__memvar_setup((void*)G__PVOID,107,0,1,-1,G__defined_typename("size_t"),-2,1,G__FastAllocString(2048).Format("SLOW_INDEX_EVENT_ID=%lluULL",(unsigned long long)xmit_event_search::SLOW_INDEX_EVENT_ID).data(),0,(char*)NULL);
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__DecoderCintLN_bin_io_handler),-1,-1,4,"_fin=",0,(char*)NULL);
   G__memvar_setup((void*)0,104,0,0,-1,G__defined_typename("word_t"),-1,4,"_target_id=",0,(char*)NULL);
   G__memvar_setup((void*)0,103,0,0,-1,-1,-1,4,"_continue_mode=",0,(char*)NULL);
   G__memvar_setup((void*)0,103,0,0,-1,-1,-1,4,"_slow_readout=",0,(char*)NULL);
   G__memvar_setup((void*)0,103,0,0,-1,-1,-1,4,"_read_by_block=",0,(char*)NULL);
   G__memvar_setup((void*)0,107,0,0,-1,G__defined_typename("size_t"),-1,4,"_index_event_id=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__DecoderCintLN_algo_base),-1,-1,4,"_algo=",0,(char*)NULL);
   }
   G__tag_memvar_reset();
}

extern "C" void G__cpp_setup_memvarDecoderCint() {
}
/***********************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
***********************************************************/

/*********************************************************
* Member function information setup for each class
*********************************************************/
static void G__setup_memfuncdecoder_manager(void) {
   /* decoder_manager */
   G__tag_memfunc_setup(G__get_linked_tagnum(&G__DecoderCintLN_decoder_manager));
   G__memfunc_setup("decoder_manager",1552,G__DecoderCint_713_0_1, 105, G__get_linked_tagnum(&G__DecoderCintLN_decoder_manager), -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("add_input_filename",1880,G__DecoderCint_713_0_2, 121, -1, -1, 0, 1, 1, 1, 0, "u 'string' - 0 - name", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("set_output_filename",2044,G__DecoderCint_713_0_3, 121, -1, -1, 0, 1, 1, 1, 0, "u 'string' - 0 - name", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("set_data_to_write",1809,G__DecoderCint_713_0_4, 121, -1, -1, 0, 2, 1, 1, 0, 
"i 'DATA_STRUCT::DATA_TYPE' - 0 - type g - - 0 'true' write", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("set_format",1076,G__DecoderCint_713_0_5, 121, -1, -1, 0, 1, 1, 1, 0, "i 'FORMAT::INPUT_FILE' - 0 - fmt", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("set_decoder",1153,G__DecoderCint_713_0_6, 121, -1, -1, 0, 1, 1, 1, 0, "U 'algo_base' - 0 - algo", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("debug_mode",1035,G__DecoderCint_713_0_7, 121, -1, -1, 0, 1, 1, 1, 0, "g - - 0 - debug", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("run",341,G__DecoderCint_713_0_8, 103, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("reset",547,G__DecoderCint_713_0_9, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("set_read_by_block",1771,G__DecoderCint_713_0_10, 121, -1, -1, 0, 1, 1, 1, 0, "g - - 0 'true' doit", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("set_read_block_size",1995,G__DecoderCint_713_0_11, 121, -1, -1, 0, 1, 1, 1, 0, "k - 'size_t' 0 - n", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("initialize",1074,(G__InterfaceMethod) NULL, 103, -1, -1, 0, 0, 1, 4, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("decode",612,(G__InterfaceMethod) NULL, 103, -1, -1, 0, 0, 1, 4, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("finalize",850,(G__InterfaceMethod) NULL, 103, -1, -1, 0, 0, 1, 4, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("open_file",945,(G__InterfaceMethod) NULL, 103, -1, -1, 0, 0, 1, 4, 0, "", (char*)NULL, (void*) NULL, 0);
   // automatic copy constructor
   G__memfunc_setup("decoder_manager", 1552, G__DecoderCint_713_0_16, (int) ('i'), G__get_linked_tagnum(&G__DecoderCintLN_decoder_manager), -1, 0, 1, 1, 1, 0, "u 'decoder_manager' - 11 - -", (char*) NULL, (void*) NULL, 0);
   // automatic destructor
   G__memfunc_setup("~decoder_manager", 1678, G__DecoderCint_713_0_17, (int) ('y'), -1, -1, 0, 0, 1, 1, 0, "", (char*) NULL, (void*) NULL, 1);
   // automatic assignment operator
   G__memfunc_setup("operator=", 937, G__DecoderCint_713_0_18, (int) ('u'), G__get_linked_tagnum(&G__DecoderCintLN_decoder_manager), -1, 1, 1, 1, 1, 0, "u 'decoder_manager' - 11 - -", (char*) NULL, (void*) NULL, 0);
   G__tag_memfunc_reset();
}

static void G__setup_memfuncxmit_event_search(void) {
   /* xmit_event_search */
   G__tag_memfunc_setup(G__get_linked_tagnum(&G__DecoderCintLN_xmit_event_search));
   G__memfunc_setup("xmit_event_search",1816,G__DecoderCint_728_0_1, 105, G__get_linked_tagnum(&G__DecoderCintLN_xmit_event_search), -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("set_target_id",1374,G__DecoderCint_728_0_2, 121, -1, -1, 0, 1, 1, 1, 0, "h - 'PMT::word_t' 0 - id", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("set_filename",1260,G__DecoderCint_728_0_3, 121, -1, -1, 0, 1, 1, 1, 0, "u 'string' - 0 - name", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("set_continue_mode",1812,G__DecoderCint_728_0_4, 121, -1, -1, 0, 1, 1, 1, 0, "g - - 0 - mode", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("set_format",1076,G__DecoderCint_728_0_5, 121, -1, -1, 0, 1, 1, 1, 0, "i 'FORMAT::INPUT_FILE' - 0 - fmt", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("set_slow_readout",1731,G__DecoderCint_728_0_6, 121, -1, -1, 0, 1, 1, 1, 0, "g - - 0 'true' slow", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("set_read_by_block",1771,G__DecoderCint_728_0_7, 121, -1, -1, 0, 1, 1, 1, 0, "g - - 0 - doit", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("run",341,G__DecoderCint_728_0_8, 103, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("print_word",1096,G__DecoderCint_728_0_9, 121, -1, -1, 0, 1, 1, 1, 0, "U 'vector<unsigned int,allocator<unsigned int> >' 'vector<PMT::word_t>' 0 - in_array", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("new_event",971,G__DecoderCint_728_0_10, 103, -1, -1, 0, 1, 1, 1, 8, "h - 'PMT::word_t' 0 - word", (char*)NULL, (void*) NULL, 0);
   // automatic copy constructor
   G__memfunc_setup("xmit_event_search", 1816, G__DecoderCint_728_0_11, (int) ('i'), G__get_linked_tagnum(&G__DecoderCintLN_xmit_event_search), -1, 0, 1, 1, 1, 0, "u 'xmit_event_search' - 11 - -", (char*) NULL, (void*) NULL, 0);
   // automatic destructor
   G__memfunc_setup("~xmit_event_search", 1942, G__DecoderCint_728_0_12, (int) ('y'), -1, -1, 0, 0, 1, 1, 0, "", (char*) NULL, (void*) NULL, 1);
   // automatic assignment operator
   G__memfunc_setup("operator=", 937, G__DecoderCint_728_0_13, (int) ('u'), G__get_linked_tagnum(&G__DecoderCintLN_xmit_event_search), -1, 1, 1, 1, 1, 0, "u 'xmit_event_search' - 11 - -", (char*) NULL, (void*) NULL, 0);
   G__tag_memfunc_reset();
}


/*********************************************************
* Member function information setup
*********************************************************/
extern "C" void G__cpp_setup_memfuncDecoderCint() {
}

/*********************************************************
* Global variable information setup for each class
*********************************************************/
static void G__cpp_setup_global0() {

   /* Setting up global variables */
   G__resetplocal();

}

static void G__cpp_setup_global1() {
}

static void G__cpp_setup_global2() {
}

static void G__cpp_setup_global3() {
}

static void G__cpp_setup_global4() {

   G__resetglobalenv();
}
extern "C" void G__cpp_setup_globalDecoderCint() {
  G__cpp_setup_global0();
  G__cpp_setup_global1();
  G__cpp_setup_global2();
  G__cpp_setup_global3();
  G__cpp_setup_global4();
}

/*********************************************************
* Global function information setup for each class
*********************************************************/
static void G__cpp_setup_func0() {
   G__lastifuncposition();

}

static void G__cpp_setup_func1() {
}

static void G__cpp_setup_func2() {
}

static void G__cpp_setup_func3() {
}

static void G__cpp_setup_func4() {
}

static void G__cpp_setup_func5() {
}

static void G__cpp_setup_func6() {
}

static void G__cpp_setup_func7() {
}

static void G__cpp_setup_func8() {
}

static void G__cpp_setup_func9() {
}

static void G__cpp_setup_func10() {
}

static void G__cpp_setup_func11() {
}

static void G__cpp_setup_func12() {
}

static void G__cpp_setup_func13() {
}

static void G__cpp_setup_func14() {
}

static void G__cpp_setup_func15() {
}

static void G__cpp_setup_func16() {
}

static void G__cpp_setup_func17() {
}

static void G__cpp_setup_func18() {
}

static void G__cpp_setup_func19() {
}

static void G__cpp_setup_func20() {
}

static void G__cpp_setup_func21() {
}

static void G__cpp_setup_func22() {
}

static void G__cpp_setup_func23() {
}

static void G__cpp_setup_func24() {
}

static void G__cpp_setup_func25() {
}

static void G__cpp_setup_func26() {
}

static void G__cpp_setup_func27() {
}

static void G__cpp_setup_func28() {

   G__resetifuncposition();
}

extern "C" void G__cpp_setup_funcDecoderCint() {
  G__cpp_setup_func0();
  G__cpp_setup_func1();
  G__cpp_setup_func2();
  G__cpp_setup_func3();
  G__cpp_setup_func4();
  G__cpp_setup_func5();
  G__cpp_setup_func6();
  G__cpp_setup_func7();
  G__cpp_setup_func8();
  G__cpp_setup_func9();
  G__cpp_setup_func10();
  G__cpp_setup_func11();
  G__cpp_setup_func12();
  G__cpp_setup_func13();
  G__cpp_setup_func14();
  G__cpp_setup_func15();
  G__cpp_setup_func16();
  G__cpp_setup_func17();
  G__cpp_setup_func18();
  G__cpp_setup_func19();
  G__cpp_setup_func20();
  G__cpp_setup_func21();
  G__cpp_setup_func22();
  G__cpp_setup_func23();
  G__cpp_setup_func24();
  G__cpp_setup_func25();
  G__cpp_setup_func26();
  G__cpp_setup_func27();
  G__cpp_setup_func28();
}

/*********************************************************
* Class,struct,union,enum tag information setup
*********************************************************/
/* Setup class/struct taginfo */
G__linked_taginfo G__DecoderCintLN_vectorlEunsignedsPshortcOallocatorlEunsignedsPshortgRsPgR = { "vector<unsigned short,allocator<unsigned short> >" , 99 , -1 };
G__linked_taginfo G__DecoderCintLN_vectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgR = { "vector<unsigned int,allocator<unsigned int> >" , 99 , -1 };
G__linked_taginfo G__DecoderCintLN_string = { "string" , 99 , -1 };
G__linked_taginfo G__DecoderCintLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR = { "vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >" , 99 , -1 };
G__linked_taginfo G__DecoderCintLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR = { "reverse_iterator<vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >::iterator>" , 99 , -1 };
G__linked_taginfo G__DecoderCintLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR = { "vector<TVirtualArray*,allocator<TVirtualArray*> >" , 99 , -1 };
G__linked_taginfo G__DecoderCintLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<TVirtualArray*,allocator<TVirtualArray*> >::iterator>" , 99 , -1 };
G__linked_taginfo G__DecoderCintLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR = { "iterator<bidirectional_iterator_tag,TObject*,long,const TObject**,const TObject*&>" , 115 , -1 };
G__linked_taginfo G__DecoderCintLN_maplEstringcOintcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOintgRsPgRsPgR = { "map<string,int,less<string>,allocator<pair<const string,int> > >" , 99 , -1 };
G__linked_taginfo G__DecoderCintLN_maplEstringcOdoublecOlesslEstringgRcOallocatorlEpairlEconstsPstringcOdoublegRsPgRsPgR = { "map<string,double,less<string>,allocator<pair<const string,double> > >" , 99 , -1 };
G__linked_taginfo G__DecoderCintLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR = { "map<string,TObjArray*,less<string>,allocator<pair<const string,TObjArray*> > >" , 99 , -1 };
G__linked_taginfo G__DecoderCintLN_FORMAT = { "FORMAT" , 110 , -1 };
G__linked_taginfo G__DecoderCintLN_FORMATcLcLINPUT_FILE = { "FORMAT::INPUT_FILE" , 101 , -1 };
G__linked_taginfo G__DecoderCintLN_DATA_STRUCT = { "DATA_STRUCT" , 110 , -1 };
G__linked_taginfo G__DecoderCintLN_DATA_STRUCTcLcLDATA_TYPE = { "DATA_STRUCT::DATA_TYPE" , 101 , -1 };
G__linked_taginfo G__DecoderCintLN_decoder_base = { "decoder_base" , 99 , -1 };
G__linked_taginfo G__DecoderCintLN_vectorlEpulse_infocOallocatorlEpulse_infogRsPgR = { "vector<pulse_info,allocator<pulse_info> >" , 99 , -1 };
G__linked_taginfo G__DecoderCintLN_reverse_iteratorlEvectorlEpulse_infocOallocatorlEpulse_infogRsPgRcLcLiteratorgR = { "reverse_iterator<vector<pulse_info,allocator<pulse_info> >::iterator>" , 99 , -1 };
G__linked_taginfo G__DecoderCintLN_vectorlEintcOallocatorlEintgRsPgR = { "vector<int,allocator<int> >" , 99 , -1 };
G__linked_taginfo G__DecoderCintLN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<int,allocator<int> >::iterator>" , 99 , -1 };
G__linked_taginfo G__DecoderCintLN_vectorlEstringcOallocatorlEstringgRsPgR = { "vector<string,allocator<string> >" , 99 , -1 };
G__linked_taginfo G__DecoderCintLN_vectorlEstringcOallocatorlEstringgRsPgRcLcLiterator = { "vector<string,allocator<string> >::iterator" , 99 , -1 };
G__linked_taginfo G__DecoderCintLN_reverse_iteratorlEvectorlEstringcOallocatorlEstringgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<string,allocator<string> >::iterator>" , 99 , -1 };
G__linked_taginfo G__DecoderCintLN_maplEstringcOstringcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOstringgRsPgRsPgR = { "map<string,string,less<string>,allocator<pair<const string,string> > >" , 99 , -1 };
G__linked_taginfo G__DecoderCintLN_maplEstringcOboolcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOboolgRsPgRsPgR = { "map<string,bool,less<string>,allocator<pair<const string,bool> > >" , 99 , -1 };
G__linked_taginfo G__DecoderCintLN_maplEstringcOvectorlEdoublecOallocatorlEdoublegRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlEdoublecOallocatorlEdoublegRsPgRsPgRsPgRsPgR = { "map<string,vector<double,allocator<double> >,less<string>,allocator<pair<const string,vector<double,allocator<double> > > > >" , 99 , -1 };
G__linked_taginfo G__DecoderCintLN_maplEstringcOvectorlEintcOallocatorlEintgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlEintcOallocatorlEintgRsPgRsPgRsPgRsPgR = { "map<string,vector<int,allocator<int> >,less<string>,allocator<pair<const string,vector<int,allocator<int> > > > >" , 99 , -1 };
G__linked_taginfo G__DecoderCintLN_maplEstringcOvectorlEstringcOallocatorlEstringgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlEstringcOallocatorlEstringgRsPgRsPgRsPgRsPgR = { "map<string,vector<string,allocator<string> >,less<string>,allocator<pair<const string,vector<string,allocator<string> > > > >" , 99 , -1 };
G__linked_taginfo G__DecoderCintLN_maplEstringcOvectorlEboolcOallocatorlEboolgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlEboolcOallocatorlEboolgRsPgRsPgRsPgRsPgR = { "map<string,vector<bool,allocator<bool> >,less<string>,allocator<pair<const string,vector<bool,allocator<bool> > > > >" , 99 , -1 };
G__linked_taginfo G__DecoderCintLN_vectorlEuser_infocOallocatorlEuser_infogRsPgR = { "vector<user_info,allocator<user_info> >" , 99 , -1 };
G__linked_taginfo G__DecoderCintLN_reverse_iteratorlEvectorlEuser_infocOallocatorlEuser_infogRsPgRcLcLiteratorgR = { "reverse_iterator<vector<user_info,allocator<user_info> >::iterator>" , 99 , -1 };
G__linked_taginfo G__DecoderCintLN_vectorlEpmt_waveformcOallocatorlEpmt_waveformgRsPgR = { "vector<pmt_waveform,allocator<pmt_waveform> >" , 99 , -1 };
G__linked_taginfo G__DecoderCintLN_reverse_iteratorlEvectorlEpmt_waveformcOallocatorlEpmt_waveformgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<pmt_waveform,allocator<pmt_waveform> >::iterator>" , 99 , -1 };
G__linked_taginfo G__DecoderCintLN_vectorlEtpc_waveformcOallocatorlEtpc_waveformgRsPgR = { "vector<tpc_waveform,allocator<tpc_waveform> >" , 99 , -1 };
G__linked_taginfo G__DecoderCintLN_reverse_iteratorlEvectorlEtpc_waveformcOallocatorlEtpc_waveformgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<tpc_waveform,allocator<tpc_waveform> >::iterator>" , 99 , -1 };
G__linked_taginfo G__DecoderCintLN_storage_manager = { "storage_manager" , 99 , -1 };
G__linked_taginfo G__DecoderCintLN_bin_io_handler = { "bin_io_handler" , 99 , -1 };
G__linked_taginfo G__DecoderCintLN_algo_base = { "algo_base" , 99 , -1 };
G__linked_taginfo G__DecoderCintLN_dequelEunsignedsPintcOallocatorlEunsignedsPintgRsPgR = { "deque<unsigned int,allocator<unsigned int> >" , 99 , -1 };
G__linked_taginfo G__DecoderCintLN_decoder_manager = { "decoder_manager" , 99 , -1 };
G__linked_taginfo G__DecoderCintLN_vectorlEana_basemUcOallocatorlEana_basemUgRsPgR = { "vector<ana_base*,allocator<ana_base*> >" , 99 , -1 };
G__linked_taginfo G__DecoderCintLN_reverse_iteratorlEvectorlEana_basemUcOallocatorlEana_basemUgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<ana_base*,allocator<ana_base*> >::iterator>" , 99 , -1 };
G__linked_taginfo G__DecoderCintLN_xmit_event_search = { "xmit_event_search" , 99 , -1 };

/* Reset class/struct taginfo */
extern "C" void G__cpp_reset_tagtableDecoderCint() {
  G__DecoderCintLN_vectorlEunsignedsPshortcOallocatorlEunsignedsPshortgRsPgR.tagnum = -1 ;
  G__DecoderCintLN_vectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgR.tagnum = -1 ;
  G__DecoderCintLN_string.tagnum = -1 ;
  G__DecoderCintLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR.tagnum = -1 ;
  G__DecoderCintLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__DecoderCintLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR.tagnum = -1 ;
  G__DecoderCintLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__DecoderCintLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR.tagnum = -1 ;
  G__DecoderCintLN_maplEstringcOintcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOintgRsPgRsPgR.tagnum = -1 ;
  G__DecoderCintLN_maplEstringcOdoublecOlesslEstringgRcOallocatorlEpairlEconstsPstringcOdoublegRsPgRsPgR.tagnum = -1 ;
  G__DecoderCintLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR.tagnum = -1 ;
  G__DecoderCintLN_FORMAT.tagnum = -1 ;
  G__DecoderCintLN_FORMATcLcLINPUT_FILE.tagnum = -1 ;
  G__DecoderCintLN_DATA_STRUCT.tagnum = -1 ;
  G__DecoderCintLN_DATA_STRUCTcLcLDATA_TYPE.tagnum = -1 ;
  G__DecoderCintLN_decoder_base.tagnum = -1 ;
  G__DecoderCintLN_vectorlEpulse_infocOallocatorlEpulse_infogRsPgR.tagnum = -1 ;
  G__DecoderCintLN_reverse_iteratorlEvectorlEpulse_infocOallocatorlEpulse_infogRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__DecoderCintLN_vectorlEintcOallocatorlEintgRsPgR.tagnum = -1 ;
  G__DecoderCintLN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__DecoderCintLN_vectorlEstringcOallocatorlEstringgRsPgR.tagnum = -1 ;
  G__DecoderCintLN_vectorlEstringcOallocatorlEstringgRsPgRcLcLiterator.tagnum = -1 ;
  G__DecoderCintLN_reverse_iteratorlEvectorlEstringcOallocatorlEstringgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__DecoderCintLN_maplEstringcOstringcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOstringgRsPgRsPgR.tagnum = -1 ;
  G__DecoderCintLN_maplEstringcOboolcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOboolgRsPgRsPgR.tagnum = -1 ;
  G__DecoderCintLN_maplEstringcOvectorlEdoublecOallocatorlEdoublegRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlEdoublecOallocatorlEdoublegRsPgRsPgRsPgRsPgR.tagnum = -1 ;
  G__DecoderCintLN_maplEstringcOvectorlEintcOallocatorlEintgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlEintcOallocatorlEintgRsPgRsPgRsPgRsPgR.tagnum = -1 ;
  G__DecoderCintLN_maplEstringcOvectorlEstringcOallocatorlEstringgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlEstringcOallocatorlEstringgRsPgRsPgRsPgRsPgR.tagnum = -1 ;
  G__DecoderCintLN_maplEstringcOvectorlEboolcOallocatorlEboolgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlEboolcOallocatorlEboolgRsPgRsPgRsPgRsPgR.tagnum = -1 ;
  G__DecoderCintLN_vectorlEuser_infocOallocatorlEuser_infogRsPgR.tagnum = -1 ;
  G__DecoderCintLN_reverse_iteratorlEvectorlEuser_infocOallocatorlEuser_infogRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__DecoderCintLN_vectorlEpmt_waveformcOallocatorlEpmt_waveformgRsPgR.tagnum = -1 ;
  G__DecoderCintLN_reverse_iteratorlEvectorlEpmt_waveformcOallocatorlEpmt_waveformgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__DecoderCintLN_vectorlEtpc_waveformcOallocatorlEtpc_waveformgRsPgR.tagnum = -1 ;
  G__DecoderCintLN_reverse_iteratorlEvectorlEtpc_waveformcOallocatorlEtpc_waveformgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__DecoderCintLN_storage_manager.tagnum = -1 ;
  G__DecoderCintLN_bin_io_handler.tagnum = -1 ;
  G__DecoderCintLN_algo_base.tagnum = -1 ;
  G__DecoderCintLN_dequelEunsignedsPintcOallocatorlEunsignedsPintgRsPgR.tagnum = -1 ;
  G__DecoderCintLN_decoder_manager.tagnum = -1 ;
  G__DecoderCintLN_vectorlEana_basemUcOallocatorlEana_basemUgRsPgR.tagnum = -1 ;
  G__DecoderCintLN_reverse_iteratorlEvectorlEana_basemUcOallocatorlEana_basemUgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__DecoderCintLN_xmit_event_search.tagnum = -1 ;
}


extern "C" void G__cpp_setup_tagtableDecoderCint() {

   /* Setting up class,struct,union tag entry */
   G__get_linked_tagnum_fwd(&G__DecoderCintLN_vectorlEunsignedsPshortcOallocatorlEunsignedsPshortgRsPgR);
   G__get_linked_tagnum_fwd(&G__DecoderCintLN_vectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgR);
   G__get_linked_tagnum_fwd(&G__DecoderCintLN_string);
   G__get_linked_tagnum_fwd(&G__DecoderCintLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR);
   G__get_linked_tagnum_fwd(&G__DecoderCintLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__DecoderCintLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR);
   G__get_linked_tagnum_fwd(&G__DecoderCintLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__DecoderCintLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR);
   G__get_linked_tagnum_fwd(&G__DecoderCintLN_maplEstringcOintcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOintgRsPgRsPgR);
   G__get_linked_tagnum_fwd(&G__DecoderCintLN_maplEstringcOdoublecOlesslEstringgRcOallocatorlEpairlEconstsPstringcOdoublegRsPgRsPgR);
   G__get_linked_tagnum_fwd(&G__DecoderCintLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR);
   G__get_linked_tagnum_fwd(&G__DecoderCintLN_FORMAT);
   G__get_linked_tagnum_fwd(&G__DecoderCintLN_FORMATcLcLINPUT_FILE);
   G__get_linked_tagnum_fwd(&G__DecoderCintLN_DATA_STRUCT);
   G__get_linked_tagnum_fwd(&G__DecoderCintLN_DATA_STRUCTcLcLDATA_TYPE);
   G__get_linked_tagnum_fwd(&G__DecoderCintLN_decoder_base);
   G__get_linked_tagnum_fwd(&G__DecoderCintLN_vectorlEpulse_infocOallocatorlEpulse_infogRsPgR);
   G__get_linked_tagnum_fwd(&G__DecoderCintLN_reverse_iteratorlEvectorlEpulse_infocOallocatorlEpulse_infogRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__DecoderCintLN_vectorlEintcOallocatorlEintgRsPgR);
   G__get_linked_tagnum_fwd(&G__DecoderCintLN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__DecoderCintLN_vectorlEstringcOallocatorlEstringgRsPgR);
   G__get_linked_tagnum_fwd(&G__DecoderCintLN_vectorlEstringcOallocatorlEstringgRsPgRcLcLiterator);
   G__get_linked_tagnum_fwd(&G__DecoderCintLN_reverse_iteratorlEvectorlEstringcOallocatorlEstringgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__DecoderCintLN_maplEstringcOstringcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOstringgRsPgRsPgR);
   G__get_linked_tagnum_fwd(&G__DecoderCintLN_maplEstringcOboolcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOboolgRsPgRsPgR);
   G__get_linked_tagnum_fwd(&G__DecoderCintLN_maplEstringcOvectorlEdoublecOallocatorlEdoublegRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlEdoublecOallocatorlEdoublegRsPgRsPgRsPgRsPgR);
   G__get_linked_tagnum_fwd(&G__DecoderCintLN_maplEstringcOvectorlEintcOallocatorlEintgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlEintcOallocatorlEintgRsPgRsPgRsPgRsPgR);
   G__get_linked_tagnum_fwd(&G__DecoderCintLN_maplEstringcOvectorlEstringcOallocatorlEstringgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlEstringcOallocatorlEstringgRsPgRsPgRsPgRsPgR);
   G__get_linked_tagnum_fwd(&G__DecoderCintLN_maplEstringcOvectorlEboolcOallocatorlEboolgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlEboolcOallocatorlEboolgRsPgRsPgRsPgRsPgR);
   G__get_linked_tagnum_fwd(&G__DecoderCintLN_vectorlEuser_infocOallocatorlEuser_infogRsPgR);
   G__get_linked_tagnum_fwd(&G__DecoderCintLN_reverse_iteratorlEvectorlEuser_infocOallocatorlEuser_infogRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__DecoderCintLN_vectorlEpmt_waveformcOallocatorlEpmt_waveformgRsPgR);
   G__get_linked_tagnum_fwd(&G__DecoderCintLN_reverse_iteratorlEvectorlEpmt_waveformcOallocatorlEpmt_waveformgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__DecoderCintLN_vectorlEtpc_waveformcOallocatorlEtpc_waveformgRsPgR);
   G__get_linked_tagnum_fwd(&G__DecoderCintLN_reverse_iteratorlEvectorlEtpc_waveformcOallocatorlEtpc_waveformgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__DecoderCintLN_storage_manager);
   G__get_linked_tagnum_fwd(&G__DecoderCintLN_bin_io_handler);
   G__get_linked_tagnum_fwd(&G__DecoderCintLN_algo_base);
   G__get_linked_tagnum_fwd(&G__DecoderCintLN_dequelEunsignedsPintcOallocatorlEunsignedsPintgRsPgR);
   G__tagtable_setup(G__get_linked_tagnum_fwd(&G__DecoderCintLN_decoder_manager),sizeof(decoder_manager),-1,263424,(char*)NULL,G__setup_memvardecoder_manager,G__setup_memfuncdecoder_manager);
   G__get_linked_tagnum_fwd(&G__DecoderCintLN_vectorlEana_basemUcOallocatorlEana_basemUgRsPgR);
   G__get_linked_tagnum_fwd(&G__DecoderCintLN_reverse_iteratorlEvectorlEana_basemUcOallocatorlEana_basemUgRsPgRcLcLiteratorgR);
   G__tagtable_setup(G__get_linked_tagnum_fwd(&G__DecoderCintLN_xmit_event_search),sizeof(xmit_event_search),-1,263424,(char*)NULL,G__setup_memvarxmit_event_search,G__setup_memfuncxmit_event_search);
}
extern "C" void G__cpp_setupDecoderCint(void) {
  G__check_setup_version(30051515,"G__cpp_setupDecoderCint()");
  G__set_cpp_environmentDecoderCint();
  G__cpp_setup_tagtableDecoderCint();

  G__cpp_setup_inheritanceDecoderCint();

  G__cpp_setup_typetableDecoderCint();

  G__cpp_setup_memvarDecoderCint();

  G__cpp_setup_memfuncDecoderCint();
  G__cpp_setup_globalDecoderCint();
  G__cpp_setup_funcDecoderCint();

   if(0==G__getsizep2memfunc()) G__get_sizep2memfuncDecoderCint();
  return;
}
class G__cpp_setup_initDecoderCint {
  public:
    G__cpp_setup_initDecoderCint() { G__add_setup_func("DecoderCint",(G__incsetup)(&G__cpp_setupDecoderCint)); G__call_setup_funcs(); }
   ~G__cpp_setup_initDecoderCint() { G__remove_setup_func("DecoderCint"); }
};
G__cpp_setup_initDecoderCint G__cpp_setup_initializerDecoderCint;

