#
# A simple example to show how one can make a for & while 'loop'.
#
import sys

#
# Looping over a list.
#

# Python "for" loop is in the form of "for x in y". 
# Here, "y" should be a list or tuple, and "x" is an element of "y"
# which becomes available in the loop. This is equivalent of using
# an iterator method in C++
y=[0,2,4,8]
print 
print 'Example 1: Looping over the element in the list',y
index=0
for x in y:
    print 'Index %d ... value =' % index, x
    index+=1
print 'Hit enter to continue.'
sys.stdin.readline()

# Instead of using an iterator equivalent method, maybe you want to
# loop over an index. The process is same: you generate an array of
# index, and loop over it. A handy tool to use here is "xrange" function
# which generates an array of length N given in the index.
print 'Example 2: Looping over the index of the list', y
print 'Index list is generated by xrange.'
for index in xrange(len(y)):
    print 'Index %d ... value=' % index, y[index]
print 'Hit enter to continue.'
sys.stdin.readline()

#
# Looping over a map
#
y={'a':0, 'b':1, 'c':2}
print "Now let's try looping over a map:",y
print "For this, we can use map.keys() function to generate a list of keys."
for x in y.keys():
    print 'key =',x,' ... value=',y[x]
print 'Hit enter to continue.'
sys.stdin.readline()

#
# while loop
#
print "Let's try while loop now."
print "We set a conter and exit the loop when counter exceeds 10."
ctr=0
while ctr<10:
    print 'ctr=',ctr
    ctr+=1
print 'Hit enter to exit.'
sys.stdin.readline()


